# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 528)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.welcomeTab = QtWidgets.QWidget()
        self.welcomeTab.setObjectName("welcomeTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.welcomeTab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appNameLabel = QtWidgets.QLabel(self.welcomeTab)
        font = QtGui.QFont()
        font.setFamily("Desdemona")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.appNameLabel.setFont(font)
        self.appNameLabel.setStyleSheet("color: rgb(20, 163, 255);")
        self.appNameLabel.setObjectName("appNameLabel")
        self.verticalLayout_2.addWidget(self.appNameLabel, 0, QtCore.Qt.AlignHCenter)
        self.versionLabel = QtWidgets.QLabel(self.welcomeTab)
        font = QtGui.QFont()
        font.setFamily("Desdemona")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setStyleSheet("color: rgb(20, 163, 255);")
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout_2.addWidget(self.versionLabel, 0, QtCore.Qt.AlignHCenter)
        self.descLabel = QtWidgets.QLabel(self.welcomeTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.descLabel.setFont(font)
        self.descLabel.setStyleSheet("")
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout_2.addWidget(self.descLabel, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.welcomeTab, "")
        self.infoGatheringTab = QtWidgets.QWidget()
        self.infoGatheringTab.setObjectName("infoGatheringTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.infoGatheringTab)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.braaLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.braaLabel.setStyleSheet("")
        self.braaLabel.setObjectName("braaLabel")
        self.gridLayout_4.addWidget(self.braaLabel, 7, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 13, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 9, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 6, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 15, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 13, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 11, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 9, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 16, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 15, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 10, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 14, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 12, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 16, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 11, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 8, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 12, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 10, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 14, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 3, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 4, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 5, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 6, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 7, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 8, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 9, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 10, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 11, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 12, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 13, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_49.setObjectName("label_49")
        self.gridLayout_4.addWidget(self.label_49, 14, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 15, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 16, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_50.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.label_50, 2, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 3, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_52.setObjectName("label_52")
        self.gridLayout_4.addWidget(self.label_52, 4, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_53.setObjectName("label_53")
        self.gridLayout_4.addWidget(self.label_53, 5, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_54.setObjectName("label_54")
        self.gridLayout_4.addWidget(self.label_54, 6, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_55.setObjectName("label_55")
        self.gridLayout_4.addWidget(self.label_55, 7, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 8, 3, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_57.setObjectName("label_57")
        self.gridLayout_4.addWidget(self.label_57, 9, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_58.setObjectName("label_58")
        self.gridLayout_4.addWidget(self.label_58, 10, 3, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_59.setObjectName("label_59")
        self.gridLayout_4.addWidget(self.label_59, 11, 3, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_60.setObjectName("label_60")
        self.gridLayout_4.addWidget(self.label_60, 12, 3, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_61.setObjectName("label_61")
        self.gridLayout_4.addWidget(self.label_61, 13, 3, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_62.setObjectName("label_62")
        self.gridLayout_4.addWidget(self.label_62, 14, 3, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_63.setObjectName("label_63")
        self.gridLayout_4.addWidget(self.label_63, 15, 3, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.infoGatheringTab)
        self.label_64.setObjectName("label_64")
        self.gridLayout_4.addWidget(self.label_64, 16, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.infoGatheringTab)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 2, 2, QtCore.Qt.AlignHCenter)
        self.braaLabel.raise_()
        self.label_17.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_15.raise_()
        self.label_4.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_21.raise_()
        self.label_23.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_30.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_14.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.label_49.raise_()
        self.label_48.raise_()
        self.label_47.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.tabWidget.addTab(self.infoGatheringTab, "")
        self.acccheckTab = QtWidgets.QWidget()
        self.acccheckTab.setObjectName("acccheckTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.acccheckTab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.acccheckTitle = QtWidgets.QLabel(self.acccheckTab)
        self.acccheckTitle.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.acccheckTitle.setFont(font)
        self.acccheckTitle.setObjectName("acccheckTitle")
        self.gridLayout_2.addWidget(self.acccheckTitle, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.acccheckTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1551, 648))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem, 9, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_6.addWidget(self.label_65, 7, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_68.setObjectName("label_68")
        self.gridLayout_6.addWidget(self.label_68, 5, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_66.setObjectName("label_66")
        self.gridLayout_6.addWidget(self.label_66, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_67.setObjectName("label_67")
        self.gridLayout_6.addWidget(self.label_67, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_69.setObjectName("label_69")
        self.gridLayout_6.addWidget(self.label_69, 6, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.acccheckTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 772, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuWindow = QtWidgets.QMenu(self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.actionClose_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_Tab.setObjectName("actionClose_Tab")
        self.actionNew_Tab = QtWidgets.QAction(MainWindow)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionEnable_Dark_Mode = QtWidgets.QAction(MainWindow)
        self.actionEnable_Dark_Mode.setObjectName("actionEnable_Dark_Mode")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionEnter_Full_Screen = QtWidgets.QAction(MainWindow)
        self.actionEnter_Full_Screen.setObjectName("actionEnter_Full_Screen")
        self.actionSelect_Next_Tab = QtWidgets.QAction(MainWindow)
        self.actionSelect_Next_Tab.setObjectName("actionSelect_Next_Tab")
        self.actionSelect_Previous_Tab = QtWidgets.QAction(MainWindow)
        self.actionSelect_Previous_Tab.setObjectName("actionSelect_Previous_Tab")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuFile.addAction(self.actionNew_Tab)
        self.menuFile.addAction(self.actionNew_Window)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_Tab)
        self.menuFile.addAction(self.actionClose_Window)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuView.addAction(self.actionEnable_Dark_Mode)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionEnter_Full_Screen)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionSelect_Next_Tab)
        self.menuWindow.addAction(self.actionSelect_Previous_Tab)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "T Y R I O N"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Kali Tools"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Information Gathering"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "acccheck"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "ace-voip"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Amap"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Automater"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "bing-ip2hosts"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "braa"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "CaseFile"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "CDPSnarf"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "cisco-torch"))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("MainWindow", "Cookie Cadger"))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("MainWindow", "copy-router-config"))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("MainWindow", "DMitry"))
        self.treeWidget.topLevelItem(0).child(12).setText(0, _translate("MainWindow", "dnmap"))
        self.treeWidget.topLevelItem(0).child(13).setText(0, _translate("MainWindow", "dsenum"))
        self.treeWidget.topLevelItem(0).child(14).setText(0, _translate("MainWindow", "dnsmap"))
        self.treeWidget.topLevelItem(0).child(15).setText(0, _translate("MainWindow", "DNSRecon"))
        self.treeWidget.topLevelItem(0).child(16).setText(0, _translate("MainWindow", "dnstracer"))
        self.treeWidget.topLevelItem(0).child(17).setText(0, _translate("MainWindow", "dnswalk"))
        self.treeWidget.topLevelItem(0).child(18).setText(0, _translate("MainWindow", "DotDotPwn"))
        self.treeWidget.topLevelItem(0).child(19).setText(0, _translate("MainWindow", "enum4linux"))
        self.treeWidget.topLevelItem(0).child(20).setText(0, _translate("MainWindow", "enumIAX"))
        self.treeWidget.topLevelItem(0).child(21).setText(0, _translate("MainWindow", "Faraday"))
        self.treeWidget.topLevelItem(0).child(22).setText(0, _translate("MainWindow", "Fierce"))
        self.treeWidget.topLevelItem(0).child(23).setText(0, _translate("MainWindow", "Firewalk"))
        self.treeWidget.topLevelItem(0).child(24).setText(0, _translate("MainWindow", "fragroute"))
        self.treeWidget.topLevelItem(0).child(25).setText(0, _translate("MainWindow", "fragrouter"))
        self.treeWidget.topLevelItem(0).child(26).setText(0, _translate("MainWindow", "Ghost Phisher"))
        self.treeWidget.topLevelItem(0).child(27).setText(0, _translate("MainWindow", "GoLismero"))
        self.treeWidget.topLevelItem(0).child(28).setText(0, _translate("MainWindow", "goofile"))
        self.treeWidget.topLevelItem(0).child(29).setText(0, _translate("MainWindow", "hping3"))
        self.treeWidget.topLevelItem(0).child(30).setText(0, _translate("MainWindow", "ident-user-enum"))
        self.treeWidget.topLevelItem(0).child(31).setText(0, _translate("MainWindow", "InTrace"))
        self.treeWidget.topLevelItem(0).child(32).setText(0, _translate("MainWindow", "iSMTP"))
        self.treeWidget.topLevelItem(0).child(33).setText(0, _translate("MainWindow", "Ibd"))
        self.treeWidget.topLevelItem(0).child(34).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(0).child(35).setText(0, _translate("MainWindow", "masscan"))
        self.treeWidget.topLevelItem(0).child(36).setText(0, _translate("MainWindow", "Metagoofil"))
        self.treeWidget.topLevelItem(0).child(37).setText(0, _translate("MainWindow", "Miranda"))
        self.treeWidget.topLevelItem(0).child(38).setText(0, _translate("MainWindow", "nbtscan-unixwiz"))
        self.treeWidget.topLevelItem(0).child(39).setText(0, _translate("MainWindow", "Nmap"))
        self.treeWidget.topLevelItem(0).child(40).setText(0, _translate("MainWindow", "ntop"))
        self.treeWidget.topLevelItem(0).child(41).setText(0, _translate("MainWindow", "p0f"))
        self.treeWidget.topLevelItem(0).child(42).setText(0, _translate("MainWindow", "Parsero"))
        self.treeWidget.topLevelItem(0).child(43).setText(0, _translate("MainWindow", "Recon-ng"))
        self.treeWidget.topLevelItem(0).child(44).setText(0, _translate("MainWindow", "SET"))
        self.treeWidget.topLevelItem(0).child(45).setText(0, _translate("MainWindow", "smtp-user-enum"))
        self.treeWidget.topLevelItem(0).child(46).setText(0, _translate("MainWindow", "snmp-check"))
        self.treeWidget.topLevelItem(0).child(47).setText(0, _translate("MainWindow", "SPARTA"))
        self.treeWidget.topLevelItem(0).child(48).setText(0, _translate("MainWindow", "sslcaudit"))
        self.treeWidget.topLevelItem(0).child(49).setText(0, _translate("MainWindow", "SSLsplit"))
        self.treeWidget.topLevelItem(0).child(50).setText(0, _translate("MainWindow", "sslstrip"))
        self.treeWidget.topLevelItem(0).child(51).setText(0, _translate("MainWindow", "SSLyze"))
        self.treeWidget.topLevelItem(0).child(52).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(0).child(53).setText(0, _translate("MainWindow", "theHarvester"))
        self.treeWidget.topLevelItem(0).child(54).setText(0, _translate("MainWindow", "TLSSLed"))
        self.treeWidget.topLevelItem(0).child(55).setText(0, _translate("MainWindow", "twofi"))
        self.treeWidget.topLevelItem(0).child(56).setText(0, _translate("MainWindow", "URLCrazy"))
        self.treeWidget.topLevelItem(0).child(57).setText(0, _translate("MainWindow", "Wireshark"))
        self.treeWidget.topLevelItem(0).child(58).setText(0, _translate("MainWindow", "WOL-E"))
        self.treeWidget.topLevelItem(0).child(59).setText(0, _translate("MainWindow", "Xplico"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Sniffing & Spoofing"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Burp Suite"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "DNSChef"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "fiked"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "hamster-sidejack"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "HexInject"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "iaxflood"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "inviteflood"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "iSMTP"))
        self.treeWidget.topLevelItem(1).child(8).setText(0, _translate("MainWindow", "isr-evilgrade"))
        self.treeWidget.topLevelItem(1).child(9).setText(0, _translate("MainWindow", "mitmproxy"))
        self.treeWidget.topLevelItem(1).child(10).setText(0, _translate("MainWindow", "ohrwurm"))
        self.treeWidget.topLevelItem(1).child(11).setText(0, _translate("MainWindow", "protos-sip"))
        self.treeWidget.topLevelItem(1).child(12).setText(0, _translate("MainWindow", "rebind"))
        self.treeWidget.topLevelItem(1).child(13).setText(0, _translate("MainWindow", "responder"))
        self.treeWidget.topLevelItem(1).child(14).setText(0, _translate("MainWindow", "rtpbreak"))
        self.treeWidget.topLevelItem(1).child(15).setText(0, _translate("MainWindow", "rtpinsertsound"))
        self.treeWidget.topLevelItem(1).child(16).setText(0, _translate("MainWindow", "rtpmixsound"))
        self.treeWidget.topLevelItem(1).child(17).setText(0, _translate("MainWindow", "sctpscan"))
        self.treeWidget.topLevelItem(1).child(18).setText(0, _translate("MainWindow", "SIPArmyKnife"))
        self.treeWidget.topLevelItem(1).child(19).setText(0, _translate("MainWindow", "SIPp"))
        self.treeWidget.topLevelItem(1).child(20).setText(0, _translate("MainWindow", "SIPVicious"))
        self.treeWidget.topLevelItem(1).child(21).setText(0, _translate("MainWindow", "SniffJoke"))
        self.treeWidget.topLevelItem(1).child(22).setText(0, _translate("MainWindow", "SSLsplit"))
        self.treeWidget.topLevelItem(1).child(23).setText(0, _translate("MainWindow", "sslstrip"))
        self.treeWidget.topLevelItem(1).child(24).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(1).child(25).setText(0, _translate("MainWindow", "VoIPHopper"))
        self.treeWidget.topLevelItem(1).child(26).setText(0, _translate("MainWindow", "WebScabar"))
        self.treeWidget.topLevelItem(1).child(27).setText(0, _translate("MainWindow", "Wifi Honey"))
        self.treeWidget.topLevelItem(1).child(28).setText(0, _translate("MainWindow", "Wireshark"))
        self.treeWidget.topLevelItem(1).child(29).setText(0, _translate("MainWindow", "xspy"))
        self.treeWidget.topLevelItem(1).child(30).setText(0, _translate("MainWindow", "Yersinia"))
        self.treeWidget.topLevelItem(1).child(31).setText(0, _translate("MainWindow", "zaproxy"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Vulnerability Analysis"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "BBQSQL"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "BED"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "cisco-auditing-tool"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "cisco-global-exploiter"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "cisco-ocs"))
        self.treeWidget.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "cisco-torch"))
        self.treeWidget.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "copy-router-config"))
        self.treeWidget.topLevelItem(2).child(7).setText(0, _translate("MainWindow", "DBPwAudit"))
        self.treeWidget.topLevelItem(2).child(8).setText(0, _translate("MainWindow", "Doona"))
        self.treeWidget.topLevelItem(2).child(9).setText(0, _translate("MainWindow", "DotDotPwn"))
        self.treeWidget.topLevelItem(2).child(10).setText(0, _translate("MainWindow", "Greenbone Security Assistant"))
        self.treeWidget.topLevelItem(2).child(11).setText(0, _translate("MainWindow", "GSD"))
        self.treeWidget.topLevelItem(2).child(12).setText(0, _translate("MainWindow", "HexorBase"))
        self.treeWidget.topLevelItem(2).child(13).setText(0, _translate("MainWindow", "Inguma"))
        self.treeWidget.topLevelItem(2).child(14).setText(0, _translate("MainWindow", "jSQL"))
        self.treeWidget.topLevelItem(2).child(15).setText(0, _translate("MainWindow", "Lynis"))
        self.treeWidget.topLevelItem(2).child(16).setText(0, _translate("MainWindow", "Nmap"))
        self.treeWidget.topLevelItem(2).child(17).setText(0, _translate("MainWindow", "ohrwurm"))
        self.treeWidget.topLevelItem(2).child(18).setText(0, _translate("MainWindow", "openvas-adminstrator"))
        self.treeWidget.topLevelItem(2).child(19).setText(0, _translate("MainWindow", "openvas-scanner"))
        self.treeWidget.topLevelItem(2).child(20).setText(0, _translate("MainWindow", "Oscanner"))
        self.treeWidget.topLevelItem(2).child(21).setText(0, _translate("MainWindow", "sfuzz"))
        self.treeWidget.topLevelItem(2).child(22).setText(0, _translate("MainWindow", "SidGuesser"))
        self.treeWidget.topLevelItem(2).child(23).setText(0, _translate("MainWindow", "SIPArmyKnife"))
        self.treeWidget.topLevelItem(2).child(24).setText(0, _translate("MainWindow", "sqlmap"))
        self.treeWidget.topLevelItem(2).child(25).setText(0, _translate("MainWindow", "Sqlninja"))
        self.treeWidget.topLevelItem(2).child(26).setText(0, _translate("MainWindow", "sqlsus"))
        self.treeWidget.topLevelItem(2).child(27).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(2).child(28).setText(0, _translate("MainWindow", "tnscmd10g"))
        self.treeWidget.topLevelItem(2).child(29).setText(0, _translate("MainWindow", "unix-privesc-check"))
        self.treeWidget.topLevelItem(2).child(30).setText(0, _translate("MainWindow", "Yersinia"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Exploitation"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Armitage"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Backdoor Factory"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "BeEF"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "cisco-auditing-tool"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "cisco-global-exploiter"))
        self.treeWidget.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "cisco-ocs"))
        self.treeWidget.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "cisco-torch"))
        self.treeWidget.topLevelItem(3).child(7).setText(0, _translate("MainWindow", "Commix"))
        self.treeWidget.topLevelItem(3).child(8).setText(0, _translate("MainWindow", "crackle"))
        self.treeWidget.topLevelItem(3).child(9).setText(0, _translate("MainWindow", "jboss-autopwn"))
        self.treeWidget.topLevelItem(3).child(10).setText(0, _translate("MainWindow", "Linux Exploit Suggester"))
        self.treeWidget.topLevelItem(3).child(11).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(3).child(12).setText(0, _translate("MainWindow", "SET"))
        self.treeWidget.topLevelItem(3).child(13).setText(0, _translate("MainWindow", "ShellNoob"))
        self.treeWidget.topLevelItem(3).child(14).setText(0, _translate("MainWindow", "sqlmap"))
        self.treeWidget.topLevelItem(3).child(15).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(3).child(16).setText(0, _translate("MainWindow", "Yersinia"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Password Attacks"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "acccheck"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Burp Suite"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "CeWL"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "chnptw"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "cisco-auditing-tool"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "CmosPwd"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("MainWindow", "creddump"))
        self.treeWidget.topLevelItem(4).child(7).setText(0, _translate("MainWindow", "crunch"))
        self.treeWidget.topLevelItem(4).child(8).setText(0, _translate("MainWindow", "DBPwAudit"))
        self.treeWidget.topLevelItem(4).child(9).setText(0, _translate("MainWindow", "findmyhash"))
        self.treeWidget.topLevelItem(4).child(10).setText(0, _translate("MainWindow", "gpp-decrypt"))
        self.treeWidget.topLevelItem(4).child(11).setText(0, _translate("MainWindow", "hash-identifier"))
        self.treeWidget.topLevelItem(4).child(12).setText(0, _translate("MainWindow", "HexorBase"))
        self.treeWidget.topLevelItem(4).child(13).setText(0, _translate("MainWindow", "THC-Hydra"))
        self.treeWidget.topLevelItem(4).child(14).setText(0, _translate("MainWindow", "John the Ripper"))
        self.treeWidget.topLevelItem(4).child(15).setText(0, _translate("MainWindow", "Johnny"))
        self.treeWidget.topLevelItem(4).child(16).setText(0, _translate("MainWindow", "keimpx"))
        self.treeWidget.topLevelItem(4).child(17).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(4).child(18).setText(0, _translate("MainWindow", "Maskprocessor"))
        self.treeWidget.topLevelItem(4).child(19).setText(0, _translate("MainWindow", "multiforcer"))
        self.treeWidget.topLevelItem(4).child(20).setText(0, _translate("MainWindow", "Ncrack"))
        self.treeWidget.topLevelItem(4).child(21).setText(0, _translate("MainWindow", "oclgausscrack"))
        self.treeWidget.topLevelItem(4).child(22).setText(0, _translate("MainWindow", "PACK"))
        self.treeWidget.topLevelItem(4).child(23).setText(0, _translate("MainWindow", "patator"))
        self.treeWidget.topLevelItem(4).child(24).setText(0, _translate("MainWindow", "phrasendrescher"))
        self.treeWidget.topLevelItem(4).child(25).setText(0, _translate("MainWindow", "polenum"))
        self.treeWidget.topLevelItem(4).child(26).setText(0, _translate("MainWindow", "RainbowCrack"))
        self.treeWidget.topLevelItem(4).child(27).setText(0, _translate("MainWindow", "rcracki-mt"))
        self.treeWidget.topLevelItem(4).child(28).setText(0, _translate("MainWindow", "RSMangler"))
        self.treeWidget.topLevelItem(4).child(29).setText(0, _translate("MainWindow", "SQLdict"))
        self.treeWidget.topLevelItem(4).child(30).setText(0, _translate("MainWindow", "Statsprocessor"))
        self.treeWidget.topLevelItem(4).child(31).setText(0, _translate("MainWindow", "THC-pptp-bruter"))
        self.treeWidget.topLevelItem(4).child(32).setText(0, _translate("MainWindow", "TrueCrack"))
        self.treeWidget.topLevelItem(4).child(33).setText(0, _translate("MainWindow", "WebScarab"))
        self.treeWidget.topLevelItem(4).child(34).setText(0, _translate("MainWindow", "wordlists"))
        self.treeWidget.topLevelItem(4).child(35).setText(0, _translate("MainWindow", "zaproxy"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Wireless Attacks"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Aircrack-ng"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Asleap"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Bluelog"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "BlueMaho"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "Bluepot"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "BlueRanger"))
        self.treeWidget.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "Bluesnarfer"))
        self.treeWidget.topLevelItem(5).child(7).setText(0, _translate("MainWindow", "Bully"))
        self.treeWidget.topLevelItem(5).child(8).setText(0, _translate("MainWindow", "coWPAtty"))
        self.treeWidget.topLevelItem(5).child(9).setText(0, _translate("MainWindow", "crackle"))
        self.treeWidget.topLevelItem(5).child(10).setText(0, _translate("MainWindow", "eapmd5pass"))
        self.treeWidget.topLevelItem(5).child(11).setText(0, _translate("MainWindow", "Fern Wifi Cracker"))
        self.treeWidget.topLevelItem(5).child(12).setText(0, _translate("MainWindow", "Ghost Phisher"))
        self.treeWidget.topLevelItem(5).child(13).setText(0, _translate("MainWindow", "GISKismet"))
        self.treeWidget.topLevelItem(5).child(14).setText(0, _translate("MainWindow", "Gqrx"))
        self.treeWidget.topLevelItem(5).child(15).setText(0, _translate("MainWindow", "gr-scan"))
        self.treeWidget.topLevelItem(5).child(16).setText(0, _translate("MainWindow", "hostapd-wpe"))
        self.treeWidget.topLevelItem(5).child(17).setText(0, _translate("MainWindow", "kalibrate-rtl"))
        self.treeWidget.topLevelItem(5).child(18).setText(0, _translate("MainWindow", "KillerBee"))
        self.treeWidget.topLevelItem(5).child(19).setText(0, _translate("MainWindow", "Kismet"))
        self.treeWidget.topLevelItem(5).child(20).setText(0, _translate("MainWindow", "mdk3"))
        self.treeWidget.topLevelItem(5).child(21).setText(0, _translate("MainWindow", "mfcuk"))
        self.treeWidget.topLevelItem(5).child(22).setText(0, _translate("MainWindow", "mfoc"))
        self.treeWidget.topLevelItem(5).child(23).setText(0, _translate("MainWindow", "mfterm"))
        self.treeWidget.topLevelItem(5).child(24).setText(0, _translate("MainWindow", "Multimon-NG"))
        self.treeWidget.topLevelItem(5).child(25).setText(0, _translate("MainWindow", "PixieWPS"))
        self.treeWidget.topLevelItem(5).child(26).setText(0, _translate("MainWindow", "Reaver"))
        self.treeWidget.topLevelItem(5).child(27).setText(0, _translate("MainWindow", "redfang"))
        self.treeWidget.topLevelItem(5).child(28).setText(0, _translate("MainWindow", "RTLSDR Scanner"))
        self.treeWidget.topLevelItem(5).child(29).setText(0, _translate("MainWindow", "Spooftooph"))
        self.treeWidget.topLevelItem(5).child(30).setText(0, _translate("MainWindow", "Wifi Honey"))
        self.treeWidget.topLevelItem(5).child(31).setText(0, _translate("MainWindow", "wifiphisher"))
        self.treeWidget.topLevelItem(5).child(32).setText(0, _translate("MainWindow", "Wifitap"))
        self.treeWidget.topLevelItem(5).child(33).setText(0, _translate("MainWindow", "Wifite"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "Forensics"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "Binwalk"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "bulk-extractor"))
        self.treeWidget.topLevelItem(6).child(2).setText(0, _translate("MainWindow", "Capstone"))
        self.treeWidget.topLevelItem(6).child(3).setText(0, _translate("MainWindow", "chntpw"))
        self.treeWidget.topLevelItem(6).child(4).setText(0, _translate("MainWindow", "Cuckoo"))
        self.treeWidget.topLevelItem(6).child(5).setText(0, _translate("MainWindow", "dc3dd"))
        self.treeWidget.topLevelItem(6).child(6).setText(0, _translate("MainWindow", "ddrescue"))
        self.treeWidget.topLevelItem(6).child(7).setText(0, _translate("MainWindow", "DFF"))
        self.treeWidget.topLevelItem(6).child(8).setText(0, _translate("MainWindow", "diStorm3"))
        self.treeWidget.topLevelItem(6).child(9).setText(0, _translate("MainWindow", "Dumpzilla"))
        self.treeWidget.topLevelItem(6).child(10).setText(0, _translate("MainWindow", "extundelete"))
        self.treeWidget.topLevelItem(6).child(11).setText(0, _translate("MainWindow", "Foremost"))
        self.treeWidget.topLevelItem(6).child(12).setText(0, _translate("MainWindow", "Galleta"))
        self.treeWidget.topLevelItem(6).child(13).setText(0, _translate("MainWindow", "Guymager"))
        self.treeWidget.topLevelItem(6).child(14).setText(0, _translate("MainWindow", "iPhone Backup Analyzer"))
        self.treeWidget.topLevelItem(6).child(15).setText(0, _translate("MainWindow", "p0f"))
        self.treeWidget.topLevelItem(6).child(16).setText(0, _translate("MainWindow", "pdf-parser"))
        self.treeWidget.topLevelItem(6).child(17).setText(0, _translate("MainWindow", "pdfid"))
        self.treeWidget.topLevelItem(6).child(18).setText(0, _translate("MainWindow", "pdgmail"))
        self.treeWidget.topLevelItem(6).child(19).setText(0, _translate("MainWindow", "peepdf"))
        self.treeWidget.topLevelItem(6).child(20).setText(0, _translate("MainWindow", "RegRipper"))
        self.treeWidget.topLevelItem(6).child(21).setText(0, _translate("MainWindow", "Volatility"))
        self.treeWidget.topLevelItem(6).child(22).setText(0, _translate("MainWindow", "Xplico"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "Maintaining Access"))
        self.treeWidget.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "CryptCat"))
        self.treeWidget.topLevelItem(7).child(1).setText(0, _translate("MainWindow", "Cymothoa"))
        self.treeWidget.topLevelItem(7).child(2).setText(0, _translate("MainWindow", "dbd"))
        self.treeWidget.topLevelItem(7).child(3).setText(0, _translate("MainWindow", "dns2tcp"))
        self.treeWidget.topLevelItem(7).child(4).setText(0, _translate("MainWindow", "http-tunnel"))
        self.treeWidget.topLevelItem(7).child(5).setText(0, _translate("MainWindow", "HTTPTunnel"))
        self.treeWidget.topLevelItem(7).child(6).setText(0, _translate("MainWindow", "Intersect"))
        self.treeWidget.topLevelItem(7).child(7).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(7).child(8).setText(0, _translate("MainWindow", "Nishang"))
        self.treeWidget.topLevelItem(7).child(9).setText(0, _translate("MainWindow", "polenum"))
        self.treeWidget.topLevelItem(7).child(10).setText(0, _translate("MainWindow", "PowerSploit"))
        self.treeWidget.topLevelItem(7).child(11).setText(0, _translate("MainWindow", "pwnat"))
        self.treeWidget.topLevelItem(7).child(12).setText(0, _translate("MainWindow", "RidEnum"))
        self.treeWidget.topLevelItem(7).child(13).setText(0, _translate("MainWindow", "sbd"))
        self.treeWidget.topLevelItem(7).child(14).setText(0, _translate("MainWindow", "U3-Pwn"))
        self.treeWidget.topLevelItem(7).child(15).setText(0, _translate("MainWindow", "Webshells"))
        self.treeWidget.topLevelItem(7).child(16).setText(0, _translate("MainWindow", "Weevely"))
        self.treeWidget.topLevelItem(7).child(17).setText(0, _translate("MainWindow", "Winexe"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "Hardware Hacking"))
        self.treeWidget.topLevelItem(8).child(0).setText(0, _translate("MainWindow", "android-sdk"))
        self.treeWidget.topLevelItem(8).child(1).setText(0, _translate("MainWindow", "apktool"))
        self.treeWidget.topLevelItem(8).child(2).setText(0, _translate("MainWindow", "Arduino"))
        self.treeWidget.topLevelItem(8).child(3).setText(0, _translate("MainWindow", "dex2jar"))
        self.treeWidget.topLevelItem(8).child(4).setText(0, _translate("MainWindow", "Sakis3G"))
        self.treeWidget.topLevelItem(8).child(5).setText(0, _translate("MainWindow", "smali"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "Web Applications"))
        self.treeWidget.topLevelItem(9).child(0).setText(0, _translate("MainWindow", "apache-users"))
        self.treeWidget.topLevelItem(9).child(1).setText(0, _translate("MainWindow", "Arachni"))
        self.treeWidget.topLevelItem(9).child(2).setText(0, _translate("MainWindow", "BBQSQL"))
        self.treeWidget.topLevelItem(9).child(3).setText(0, _translate("MainWindow", "BlindElephant"))
        self.treeWidget.topLevelItem(9).child(4).setText(0, _translate("MainWindow", "Burp Suite"))
        self.treeWidget.topLevelItem(9).child(5).setText(0, _translate("MainWindow", "CutyCapt"))
        self.treeWidget.topLevelItem(9).child(6).setText(0, _translate("MainWindow", "DAVTest"))
        self.treeWidget.topLevelItem(9).child(7).setText(0, _translate("MainWindow", "deblaze"))
        self.treeWidget.topLevelItem(9).child(8).setText(0, _translate("MainWindow", "DIRB"))
        self.treeWidget.topLevelItem(9).child(9).setText(0, _translate("MainWindow", "DirBuster"))
        self.treeWidget.topLevelItem(9).child(10).setText(0, _translate("MainWindow", "fimap"))
        self.treeWidget.topLevelItem(9).child(11).setText(0, _translate("MainWindow", "FunkLoad"))
        self.treeWidget.topLevelItem(9).child(12).setText(0, _translate("MainWindow", "Gobuster"))
        self.treeWidget.topLevelItem(9).child(13).setText(0, _translate("MainWindow", "Grabber"))
        self.treeWidget.topLevelItem(9).child(14).setText(0, _translate("MainWindow", "jboss-autopwn"))
        self.treeWidget.topLevelItem(9).child(15).setText(0, _translate("MainWindow", "joomscan"))
        self.treeWidget.topLevelItem(9).child(16).setText(0, _translate("MainWindow", "jSQL"))
        self.treeWidget.topLevelItem(9).child(17).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(9).child(18).setText(0, _translate("MainWindow", "PadBuster"))
        self.treeWidget.topLevelItem(9).child(19).setText(0, _translate("MainWindow", "Paros"))
        self.treeWidget.topLevelItem(9).child(20).setText(0, _translate("MainWindow", "Parsero"))
        self.treeWidget.topLevelItem(9).child(21).setText(0, _translate("MainWindow", "plecost"))
        self.treeWidget.topLevelItem(9).child(22).setText(0, _translate("MainWindow", "Powerfuzzer"))
        self.treeWidget.topLevelItem(9).child(23).setText(0, _translate("MainWindow", "ProxyStrike"))
        self.treeWidget.topLevelItem(9).child(24).setText(0, _translate("MainWindow", "Recon-ng"))
        self.treeWidget.topLevelItem(9).child(25).setText(0, _translate("MainWindow", "Skipfish"))
        self.treeWidget.topLevelItem(9).child(26).setText(0, _translate("MainWindow", "sqlmap"))
        self.treeWidget.topLevelItem(9).child(27).setText(0, _translate("MainWindow", "Sqlninja"))
        self.treeWidget.topLevelItem(9).child(28).setText(0, _translate("MainWindow", "sqlsus"))
        self.treeWidget.topLevelItem(9).child(29).setText(0, _translate("MainWindow", "ua-tester"))
        self.treeWidget.topLevelItem(9).child(30).setText(0, _translate("MainWindow", "Uniscan"))
        self.treeWidget.topLevelItem(9).child(31).setText(0, _translate("MainWindow", "Vega"))
        self.treeWidget.topLevelItem(9).child(32).setText(0, _translate("MainWindow", "w3af"))
        self.treeWidget.topLevelItem(9).child(33).setText(0, _translate("MainWindow", "WebScarab"))
        self.treeWidget.topLevelItem(9).child(34).setText(0, _translate("MainWindow", "Webshag"))
        self.treeWidget.topLevelItem(9).child(35).setText(0, _translate("MainWindow", "WebSlayer"))
        self.treeWidget.topLevelItem(9).child(36).setText(0, _translate("MainWindow", "WebSploit"))
        self.treeWidget.topLevelItem(9).child(37).setText(0, _translate("MainWindow", "Wfuzz"))
        self.treeWidget.topLevelItem(9).child(38).setText(0, _translate("MainWindow", "WPScan"))
        self.treeWidget.topLevelItem(9).child(39).setText(0, _translate("MainWindow", "XSSer"))
        self.treeWidget.topLevelItem(9).child(40).setText(0, _translate("MainWindow", "zaproxy"))
        self.treeWidget.topLevelItem(10).setText(0, _translate("MainWindow", "Stress Testing"))
        self.treeWidget.topLevelItem(10).child(0).setText(0, _translate("MainWindow", "DHCPig"))
        self.treeWidget.topLevelItem(10).child(1).setText(0, _translate("MainWindow", "FunkLoad"))
        self.treeWidget.topLevelItem(10).child(2).setText(0, _translate("MainWindow", "iaxflood"))
        self.treeWidget.topLevelItem(10).child(3).setText(0, _translate("MainWindow", "Inundator"))
        self.treeWidget.topLevelItem(10).child(4).setText(0, _translate("MainWindow", "inviteflood"))
        self.treeWidget.topLevelItem(10).child(5).setText(0, _translate("MainWindow", "ipv6-toolkit"))
        self.treeWidget.topLevelItem(10).child(6).setText(0, _translate("MainWindow", "mdk3"))
        self.treeWidget.topLevelItem(10).child(7).setText(0, _translate("MainWindow", "Reaver"))
        self.treeWidget.topLevelItem(10).child(8).setText(0, _translate("MainWindow", "rtpflood"))
        self.treeWidget.topLevelItem(10).child(9).setText(0, _translate("MainWindow", "SlowHTTPTest"))
        self.treeWidget.topLevelItem(10).child(10).setText(0, _translate("MainWindow", "t50"))
        self.treeWidget.topLevelItem(10).child(11).setText(0, _translate("MainWindow", "Termineter"))
        self.treeWidget.topLevelItem(10).child(12).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(10).child(13).setText(0, _translate("MainWindow", "THC-SSL-DOS"))
        self.treeWidget.topLevelItem(11).setText(0, _translate("MainWindow", "Reverse Engineering"))
        self.treeWidget.topLevelItem(11).child(0).setText(0, _translate("MainWindow", "apktool"))
        self.treeWidget.topLevelItem(11).child(1).setText(0, _translate("MainWindow", "dex2jar"))
        self.treeWidget.topLevelItem(11).child(2).setText(0, _translate("MainWindow", "diStorm3"))
        self.treeWidget.topLevelItem(11).child(3).setText(0, _translate("MainWindow", "edb-debugger"))
        self.treeWidget.topLevelItem(11).child(4).setText(0, _translate("MainWindow", "jad"))
        self.treeWidget.topLevelItem(11).child(5).setText(0, _translate("MainWindow", "javasnoop"))
        self.treeWidget.topLevelItem(11).child(6).setText(0, _translate("MainWindow", "JD-GUI"))
        self.treeWidget.topLevelItem(11).child(7).setText(0, _translate("MainWindow", "OllyDbg"))
        self.treeWidget.topLevelItem(11).child(8).setText(0, _translate("MainWindow", "smali"))
        self.treeWidget.topLevelItem(11).child(9).setText(0, _translate("MainWindow", "Valgrind"))
        self.treeWidget.topLevelItem(11).child(10).setText(0, _translate("MainWindow", "YARA"))
        self.treeWidget.topLevelItem(12).setText(0, _translate("MainWindow", "Reporting"))
        self.treeWidget.topLevelItem(12).child(0).setText(0, _translate("MainWindow", "CaseFile"))
        self.treeWidget.topLevelItem(12).child(1).setText(0, _translate("MainWindow", "CutyCapt"))
        self.treeWidget.topLevelItem(12).child(2).setText(0, _translate("MainWindow", "dos2unix"))
        self.treeWidget.topLevelItem(12).child(3).setText(0, _translate("MainWindow", "Dradis"))
        self.treeWidget.topLevelItem(12).child(4).setText(0, _translate("MainWindow", "KeepNote"))
        self.treeWidget.topLevelItem(12).child(5).setText(0, _translate("MainWindow", "MagicTree"))
        self.treeWidget.topLevelItem(12).child(6).setText(0, _translate("MainWindow", "Metagoofil"))
        self.treeWidget.topLevelItem(12).child(7).setText(0, _translate("MainWindow", "Nipper-ng"))
        self.treeWidget.topLevelItem(12).child(8).setText(0, _translate("MainWindow", "pipal"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.appNameLabel.setText(_translate("MainWindow", "T Y R I O N"))
        self.versionLabel.setText(_translate("MainWindow", "V e r s i o n   1 . 0"))
        self.descLabel.setText(_translate("MainWindow", "AN ALL-IN-ONE KALI LINUX TOOL MANAGEMENT APP "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcomeTab), _translate("MainWindow", "Welcome"))
        self.braaLabel.setText(_translate("MainWindow", "braa"))
        self.label_16.setText(_translate("MainWindow", "DMitry"))
        self.label_7.setText(_translate("MainWindow", "Amap"))
        self.label_12.setText(_translate("MainWindow", "CDPSnarf"))
        self.label_25.setText(_translate("MainWindow", "enum4linux"))
        self.label_20.setText(_translate("MainWindow", "dsenum"))
        self.label_31.setText(_translate("MainWindow", "Ghost Phisher"))
        self.label_15.setText(_translate("MainWindow", "Cookie Cadger"))
        self.label_27.setText(_translate("MainWindow", "Fierce"))
        self.label_21.setText(_translate("MainWindow", "DNSRecon"))
        self.label_34.setText(_translate("MainWindow", "hping3"))
        self.label_23.setText(_translate("MainWindow", "dnstracer"))
        self.label_33.setText(_translate("MainWindow", "goofile"))
        self.label_6.setText(_translate("MainWindow", "ace-voip"))
        self.label_11.setText(_translate("MainWindow", "CaseFile"))
        self.label_8.setText(_translate("MainWindow", "Automater"))
        self.label_26.setText(_translate("MainWindow", "enumIAX"))
        self.label_9.setText(_translate("MainWindow", "bing-ip2hosts"))
        self.label_28.setText(_translate("MainWindow", "Firewalk"))
        self.label_32.setText(_translate("MainWindow", "GoLismero"))
        self.label_14.setText(_translate("MainWindow", "fragrouter"))
        self.label_19.setText(_translate("MainWindow", "dnsmap"))
        self.label_29.setText(_translate("MainWindow", "fragroute"))
        self.label_30.setText(_translate("MainWindow", "Faraday"))
        self.label_17.setText(_translate("MainWindow", "copy-router-config"))
        self.label_13.setText(_translate("MainWindow", "cisco-torch"))
        self.label_22.setText(_translate("MainWindow", "dnswalk"))
        self.label_5.setText(_translate("MainWindow", "acccheck"))
        self.label_24.setText(_translate("MainWindow", "DotDotPwn"))
        self.label_18.setText(_translate("MainWindow", "dnmap"))
        self.label_35.setText(_translate("MainWindow", "ident-user-enum"))
        self.label_36.setText(_translate("MainWindow", "InTrace"))
        self.label_37.setText(_translate("MainWindow", "iSMTP"))
        self.label_38.setText(_translate("MainWindow", "Ibd"))
        self.label_39.setText(_translate("MainWindow", "Maltego Teeth"))
        self.label_40.setText(_translate("MainWindow", "masscan"))
        self.label_41.setText(_translate("MainWindow", "Metagoofil"))
        self.label_42.setText(_translate("MainWindow", "Miranda"))
        self.label_43.setText(_translate("MainWindow", "nbtscan-unixwiz"))
        self.label_44.setText(_translate("MainWindow", "Nmap"))
        self.label_45.setText(_translate("MainWindow", "ntop"))
        self.label_46.setText(_translate("MainWindow", "p0f"))
        self.label_49.setText(_translate("MainWindow", "Parsero"))
        self.label_48.setText(_translate("MainWindow", "Recon-ng"))
        self.label_47.setText(_translate("MainWindow", "SET"))
        self.label_50.setText(_translate("MainWindow", "smtp-user-enum"))
        self.label_51.setText(_translate("MainWindow", "snmp-check"))
        self.label_52.setText(_translate("MainWindow", "SPARTA"))
        self.label_53.setText(_translate("MainWindow", "sslcaudit"))
        self.label_54.setText(_translate("MainWindow", "SSLsplit"))
        self.label_55.setText(_translate("MainWindow", "sslstrip"))
        self.label_56.setText(_translate("MainWindow", "SSLyze"))
        self.label_57.setText(_translate("MainWindow", "THC-IPV6"))
        self.label_58.setText(_translate("MainWindow", "theHarvester"))
        self.label_59.setText(_translate("MainWindow", "TLSSLed"))
        self.label_60.setText(_translate("MainWindow", "twofi"))
        self.label_61.setText(_translate("MainWindow", "URLCrazy"))
        self.label_62.setText(_translate("MainWindow", "Wireshark"))
        self.label_63.setText(_translate("MainWindow", "WOL-E"))
        self.label_64.setText(_translate("MainWindow", "Xplico"))
        self.label_4.setText(_translate("MainWindow", "Information Gathering"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoGatheringTab), _translate("MainWindow", "Information Gathering"))
        self.acccheckTitle.setText(_translate("MainWindow", "acccheck"))
        self.pushButton.setText(_translate("MainWindow", "./accheck"))
        self.label_65.setText(_translate("MainWindow", "RUN ON TERMINAL :"))
        self.label_68.setText(_translate("MainWindow", "Attempt the \'Administrator\' account with a [BLANK] password.\n"
"acccheck -t 10.10.10.1\n"
"Attempt all passwords in \'password.txt\' against the \'Administrator\' account.\n"
"acccheck -t 10.10.10.1 -P password.txt\n"
"Attempt all password in \'password.txt\' against all users in \'users.txt\'.\n"
"acccehck -t 10.10.10.1 -U users.txt -P password.txt\n"
"Attempt a single password against a single user.\n"
"acccheck -t 10.10.10.1 -u administrator -p password "))
        self.label_66.setText(_translate("MainWindow", "acccheck v0.2.1 - By Faiz\n"
"\n"
"The tool is designed as a password dictionary attack tool that targets windows\n"
"authentication via the SMB protocol. It is really a wrapper script around\n"
"the ‘smbclient’ binary, and as a result is dependent on it for its execution.\n"
"\n"
"Attempts to connect to the IPC$ and ADMIN$ shares depending on which\n"
"flags have been chosen, and tries a combination of usernames and passwords\n"
"in the hope to identify the password to a given account via a dictionary password\n"
"guessing attack.\n"
""))
        self.label_3.setText(_translate("MainWindow", "Usage:"))
        self.label_2.setText(_translate("MainWindow", "Description:"))
        self.label_67.setText(_translate("MainWindow", "./acccheck [optional]\n"
"\n"
"-t [single host IP address]\n"
"OR\n"
"-T [file containing target ip address(es)]\n"
"\n"
"Optional:\n"
"-p [single password]\n"
"-P [file containing passwords]\n"
"-u [single user]\n"
"-U [file containing usernames]\n"
"-v [verbose mode] "))
        self.label_10.setText(_translate("MainWindow", "Examples:"))
        self.label_69.setText(_translate("MainWindow", "root@kali:~# acccheck.pl -T smb-ips.txt -v\n"
"Host:192.168.1.201, Username:Administrator, Password:BLANK\n"
""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acccheckTab), _translate("MainWindow", "acccheck"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionClose_Window.setText(_translate("MainWindow", "Close Window"))
        self.actionClose_Tab.setText(_translate("MainWindow", "Close Tab"))
        self.actionNew_Tab.setText(_translate("MainWindow", "New Tab"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionEnable_Dark_Mode.setText(_translate("MainWindow", "Enable Dark Mode"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionEnter_Full_Screen.setText(_translate("MainWindow", "Enter Full Screen"))
        self.actionSelect_Next_Tab.setText(_translate("MainWindow", "Select Next Tab"))
        self.actionSelect_Previous_Tab.setText(_translate("MainWindow", "Select Previous Tab"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))

