# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 528)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.welcomeTab = QtWidgets.QWidget()
        self.welcomeTab.setObjectName("welcomeTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.welcomeTab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appNameLabel = QtWidgets.QLabel(self.welcomeTab)
        font = QtGui.QFont()
        font.setFamily("Desdemona")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.appNameLabel.setFont(font)
        self.appNameLabel.setStyleSheet("color: rgb(20, 163, 255);")
        self.appNameLabel.setObjectName("appNameLabel")
        self.verticalLayout_2.addWidget(self.appNameLabel, 0, QtCore.Qt.AlignHCenter)
        self.versionLabel = QtWidgets.QLabel(self.welcomeTab)
        font = QtGui.QFont()
        font.setFamily("Desdemona")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setStyleSheet("color: rgb(20, 163, 255);")
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout_2.addWidget(self.versionLabel, 0, QtCore.Qt.AlignHCenter)
        self.descLabel = QtWidgets.QLabel(self.welcomeTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.descLabel.setFont(font)
        self.descLabel.setStyleSheet("")
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout_2.addWidget(self.descLabel, 0, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.welcomeTab, "")
        self.infoGatheringTab = QtWidgets.QWidget()
        self.infoGatheringTab.setObjectName("infoGatheringTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.infoGatheringTab)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.braaLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.braaLabel.setStyleSheet("")
        self.braaLabel.setObjectName("braaLabel")
        self.gridLayout_4.addWidget(self.braaLabel, 7, 0, 1, 1)
        self.DMitryLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.DMitryLabel.setObjectName("DMitryLabel")
        self.gridLayout_4.addWidget(self.DMitryLabel, 13, 0, 1, 1)
        self.AmapLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.AmapLabel.setStyleSheet("")
        self.AmapLabel.setObjectName("AmapLabel")
        self.gridLayout_4.addWidget(self.AmapLabel, 5, 0, 1, 1)
        self.CDPSnarfLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.CDPSnarfLabel.setStyleSheet("")
        self.CDPSnarfLabel.setObjectName("CDPSnarfLabel")
        self.gridLayout_4.addWidget(self.CDPSnarfLabel, 9, 0, 1, 1)
        self.enum4linuxLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.enum4linuxLabel.setObjectName("enum4linuxLabel")
        self.gridLayout_4.addWidget(self.enum4linuxLabel, 6, 1, 1, 1)
        self.dsenumLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.dsenumLabel.setObjectName("dsenumLabel")
        self.gridLayout_4.addWidget(self.dsenumLabel, 15, 0, 1, 1)
        self.GhostPhisherLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.GhostPhisherLabel.setObjectName("GhostPhisherLabel")
        self.gridLayout_4.addWidget(self.GhostPhisherLabel, 13, 1, 1, 1)
        self.CookieCadgerLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.CookieCadgerLabel.setObjectName("CookieCadgerLabel")
        self.gridLayout_4.addWidget(self.CookieCadgerLabel, 11, 0, 1, 1)
        self.FierceLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.FierceLabel.setObjectName("FierceLabel")
        self.gridLayout_4.addWidget(self.FierceLabel, 9, 1, 1, 1)
        self.DNSReconLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.DNSReconLabel.setObjectName("DNSReconLabel")
        self.gridLayout_4.addWidget(self.DNSReconLabel, 2, 1, 1, 1)
        self.hping3Label = QtWidgets.QLabel(self.infoGatheringTab)
        self.hping3Label.setObjectName("hping3Label")
        self.gridLayout_4.addWidget(self.hping3Label, 16, 1, 1, 1)
        self.dnstracerLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.dnstracerLabel.setObjectName("dnstracerLabel")
        self.gridLayout_4.addWidget(self.dnstracerLabel, 3, 1, 1, 1)
        self.goofileLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.goofileLabel.setObjectName("goofileLabel")
        self.gridLayout_4.addWidget(self.goofileLabel, 15, 1, 1, 1)
        self.aceVoipLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.aceVoipLabel.setStyleSheet("")
        self.aceVoipLabel.setObjectName("aceVoipLabel")
        self.gridLayout_4.addWidget(self.aceVoipLabel, 3, 0, 1, 1)
        self.CaseFileLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.CaseFileLabel.setStyleSheet("")
        self.CaseFileLabel.setObjectName("CaseFileLabel")
        self.gridLayout_4.addWidget(self.CaseFileLabel, 8, 0, 1, 1)
        self.AutomaterLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.AutomaterLabel.setStyleSheet("")
        self.AutomaterLabel.setObjectName("AutomaterLabel")
        self.gridLayout_4.addWidget(self.AutomaterLabel, 4, 0, 1, 1)
        self.enumIAXLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.enumIAXLabel.setObjectName("enumIAXLabel")
        self.gridLayout_4.addWidget(self.enumIAXLabel, 7, 1, 1, 1)
        self.bingIp2hostsLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.bingIp2hostsLabel.setStyleSheet("")
        self.bingIp2hostsLabel.setObjectName("bingIp2hostsLabel")
        self.gridLayout_4.addWidget(self.bingIp2hostsLabel, 6, 0, 1, 1)
        self.FireWalkLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.FireWalkLabel.setObjectName("FireWalkLabel")
        self.gridLayout_4.addWidget(self.FireWalkLabel, 10, 1, 1, 1)
        self.GoLismero = QtWidgets.QLabel(self.infoGatheringTab)
        self.GoLismero.setObjectName("GoLismero")
        self.gridLayout_4.addWidget(self.GoLismero, 14, 1, 1, 1)
        self.fragRouterLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.fragRouterLabel.setObjectName("fragRouterLabel")
        self.gridLayout_4.addWidget(self.fragRouterLabel, 12, 1, 1, 1)
        self.dnsmapLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.dnsmapLabel.setObjectName("dnsmapLabel")
        self.gridLayout_4.addWidget(self.dnsmapLabel, 16, 0, 1, 1)
        self.fragRouteLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.fragRouteLabel.setObjectName("fragRouteLabel")
        self.gridLayout_4.addWidget(self.fragRouteLabel, 11, 1, 1, 1)
        self.FaradayLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.FaradayLabel.setStyleSheet("")
        self.FaradayLabel.setObjectName("FaradayLabel")
        self.gridLayout_4.addWidget(self.FaradayLabel, 8, 1, 1, 1)
        self.copyRouterConfigLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.copyRouterConfigLabel.setObjectName("copyRouterConfigLabel")
        self.gridLayout_4.addWidget(self.copyRouterConfigLabel, 12, 0, 1, 1)
        self.ciscoTorchLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.ciscoTorchLabel.setStyleSheet("")
        self.ciscoTorchLabel.setObjectName("ciscoTorchLabel")
        self.gridLayout_4.addWidget(self.ciscoTorchLabel, 10, 0, 1, 1)
        self.dnswalkLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.dnswalkLabel.setObjectName("dnswalkLabel")
        self.gridLayout_4.addWidget(self.dnswalkLabel, 4, 1, 1, 1)
        self.acccheckLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.acccheckLabel.setStyleSheet("")
        self.acccheckLabel.setObjectName("acccheckLabel")
        self.gridLayout_4.addWidget(self.acccheckLabel, 2, 0, 1, 1)
        self.DotDotPwnLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.DotDotPwnLabel.setObjectName("DotDotPwnLabel")
        self.gridLayout_4.addWidget(self.DotDotPwnLabel, 5, 1, 1, 1)
        self.dnmapLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.dnmapLabel.setObjectName("dnmapLabel")
        self.gridLayout_4.addWidget(self.dnmapLabel, 14, 0, 1, 1)
        self.identUserEnumLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.identUserEnumLabel.setObjectName("identUserEnumLabel")
        self.gridLayout_4.addWidget(self.identUserEnumLabel, 2, 2, 1, 1)
        self.InTraceLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.InTraceLabel.setObjectName("InTraceLabel")
        self.gridLayout_4.addWidget(self.InTraceLabel, 3, 2, 1, 1)
        self.SMTPLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.SMTPLabel.setObjectName("SMTPLabel")
        self.gridLayout_4.addWidget(self.SMTPLabel, 4, 2, 1, 1)
        self.IbdLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.IbdLabel.setObjectName("IbdLabel")
        self.gridLayout_4.addWidget(self.IbdLabel, 5, 2, 1, 1)
        self.MaltegoTeethLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.MaltegoTeethLabel.setObjectName("MaltegoTeethLabel")
        self.gridLayout_4.addWidget(self.MaltegoTeethLabel, 6, 2, 1, 1)
        self.masscanLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.masscanLabel.setObjectName("masscanLabel")
        self.gridLayout_4.addWidget(self.masscanLabel, 7, 2, 1, 1)
        self.MetagoofilLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.MetagoofilLabel.setObjectName("MetagoofilLabel")
        self.gridLayout_4.addWidget(self.MetagoofilLabel, 8, 2, 1, 1)
        self.MirandaLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.MirandaLabel.setObjectName("MirandaLabel")
        self.gridLayout_4.addWidget(self.MirandaLabel, 9, 2, 1, 1)
        self.nbtscanUnixwizLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.nbtscanUnixwizLabel.setObjectName("nbtscanUnixwizLabel")
        self.gridLayout_4.addWidget(self.nbtscanUnixwizLabel, 10, 2, 1, 1)
        self.NmapLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.NmapLabel.setObjectName("NmapLabel")
        self.gridLayout_4.addWidget(self.NmapLabel, 11, 2, 1, 1)
        self.ntopLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.ntopLabel.setObjectName("ntopLabel")
        self.gridLayout_4.addWidget(self.ntopLabel, 12, 2, 1, 1)
        self.p0fLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.p0fLabel.setObjectName("p0fLabel")
        self.gridLayout_4.addWidget(self.p0fLabel, 13, 2, 1, 1)
        self.ParseroLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.ParseroLabel.setObjectName("ParseroLabel")
        self.gridLayout_4.addWidget(self.ParseroLabel, 14, 2, 1, 1)
        self.ReconNgLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.ReconNgLabel.setObjectName("ReconNgLabel")
        self.gridLayout_4.addWidget(self.ReconNgLabel, 15, 2, 1, 1)
        self.SETLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.SETLabel.setObjectName("SETLabel")
        self.gridLayout_4.addWidget(self.SETLabel, 16, 2, 1, 1)
        self.smtpUserEnumLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.smtpUserEnumLabel.setObjectName("smtpUserEnumLabel")
        self.gridLayout_4.addWidget(self.smtpUserEnumLabel, 2, 3, 1, 1)
        self.snmpCheckLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.snmpCheckLabel.setObjectName("snmpCheckLabel")
        self.gridLayout_4.addWidget(self.snmpCheckLabel, 3, 3, 1, 1)
        self.SPARTALabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.SPARTALabel.setObjectName("SPARTALabel")
        self.gridLayout_4.addWidget(self.SPARTALabel, 4, 3, 1, 1)
        self.sslcauditLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.sslcauditLabel.setObjectName("sslcauditLabel")
        self.gridLayout_4.addWidget(self.sslcauditLabel, 5, 3, 1, 1)
        self.SSLsplitLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.SSLsplitLabel.setObjectName("SSLsplitLabel")
        self.gridLayout_4.addWidget(self.SSLsplitLabel, 6, 3, 1, 1)
        self.sslstripLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.sslstripLabel.setObjectName("sslstripLabel")
        self.gridLayout_4.addWidget(self.sslstripLabel, 7, 3, 1, 1)
        self.SSLyzeLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.SSLyzeLabel.setObjectName("SSLyzeLabel")
        self.gridLayout_4.addWidget(self.SSLyzeLabel, 8, 3, 1, 1)
        self.THCIPV6Label = QtWidgets.QLabel(self.infoGatheringTab)
        self.THCIPV6Label.setObjectName("THCIPV6Label")
        self.gridLayout_4.addWidget(self.THCIPV6Label, 9, 3, 1, 1)
        self.theHarvesterLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.theHarvesterLabel.setObjectName("theHarvesterLabel")
        self.gridLayout_4.addWidget(self.theHarvesterLabel, 10, 3, 1, 1)
        self.TLSSLedLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.TLSSLedLabel.setObjectName("TLSSLedLabel")
        self.gridLayout_4.addWidget(self.TLSSLedLabel, 11, 3, 1, 1)
        self.twofiLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.twofiLabel.setObjectName("twofiLabel")
        self.gridLayout_4.addWidget(self.twofiLabel, 12, 3, 1, 1)
        self.URLCrazyLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.URLCrazyLabel.setObjectName("URLCrazyLabel")
        self.gridLayout_4.addWidget(self.URLCrazyLabel, 13, 3, 1, 1)
        self.WiresharkLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.WiresharkLabel.setObjectName("WiresharkLabel")
        self.gridLayout_4.addWidget(self.WiresharkLabel, 14, 3, 1, 1)
        self.WOLELabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.WOLELabel.setObjectName("WOLELabel")
        self.gridLayout_4.addWidget(self.WOLELabel, 15, 3, 1, 1)
        self.XplicoLabel = QtWidgets.QLabel(self.infoGatheringTab)
        self.XplicoLabel.setObjectName("XplicoLabel")
        self.gridLayout_4.addWidget(self.XplicoLabel, 16, 3, 1, 1)
        self.InformationGatheringTitle = QtWidgets.QLabel(self.infoGatheringTab)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.InformationGatheringTitle.setFont(font)
        self.InformationGatheringTitle.setStyleSheet("")
        self.InformationGatheringTitle.setObjectName("InformationGatheringTitle")
        self.gridLayout_4.addWidget(self.InformationGatheringTitle, 0, 1, 2, 2, QtCore.Qt.AlignHCenter)
        self.braaLabel.raise_()
        self.copyRouterConfigLabel.raise_()
        self.acccheckLabel.raise_()
        self.aceVoipLabel.raise_()
        self.AutomaterLabel.raise_()
        self.AmapLabel.raise_()
        self.bingIp2hostsLabel.raise_()
        self.CaseFileLabel.raise_()
        self.DMitryLabel.raise_()
        self.dnmapLabel.raise_()
        self.CDPSnarfLabel.raise_()
        self.ciscoTorchLabel.raise_()
        self.CookieCadgerLabel.raise_()
        self.InformationGatheringTitle.raise_()
        self.dsenumLabel.raise_()
        self.dnsmapLabel.raise_()
        self.DNSReconLabel.raise_()
        self.dnstracerLabel.raise_()
        self.dnswalkLabel.raise_()
        self.DotDotPwnLabel.raise_()
        self.enum4linuxLabel.raise_()
        self.enumIAXLabel.raise_()
        self.FaradayLabel.raise_()
        self.FierceLabel.raise_()
        self.FireWalkLabel.raise_()
        self.fragRouteLabel.raise_()
        self.fragRouterLabel.raise_()
        self.GhostPhisherLabel.raise_()
        self.GoLismero.raise_()
        self.goofileLabel.raise_()
        self.hping3Label.raise_()
        self.identUserEnumLabel.raise_()
        self.InTraceLabel.raise_()
        self.SMTPLabel.raise_()
        self.IbdLabel.raise_()
        self.MaltegoTeethLabel.raise_()
        self.masscanLabel.raise_()
        self.MetagoofilLabel.raise_()
        self.MirandaLabel.raise_()
        self.nbtscanUnixwizLabel.raise_()
        self.NmapLabel.raise_()
        self.ntopLabel.raise_()
        self.p0fLabel.raise_()
        self.ParseroLabel.raise_()
        self.ReconNgLabel.raise_()
        self.SETLabel.raise_()
        self.smtpUserEnumLabel.raise_()
        self.snmpCheckLabel.raise_()
        self.SPARTALabel.raise_()
        self.sslcauditLabel.raise_()
        self.SSLsplitLabel.raise_()
        self.sslstripLabel.raise_()
        self.SSLyzeLabel.raise_()
        self.THCIPV6Label.raise_()
        self.theHarvesterLabel.raise_()
        self.TLSSLedLabel.raise_()
        self.twofiLabel.raise_()
        self.URLCrazyLabel.raise_()
        self.WiresharkLabel.raise_()
        self.WOLELabel.raise_()
        self.XplicoLabel.raise_()
        self.tabWidget.addTab(self.infoGatheringTab, "")
        self.acccheckTab = QtWidgets.QWidget()
        self.acccheckTab.setObjectName("acccheckTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.acccheckTab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.acccheckTitle = QtWidgets.QLabel(self.acccheckTab)
        self.acccheckTitle.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.acccheckTitle.setFont(font)
        self.acccheckTitle.setObjectName("acccheckTitle")
        self.gridLayout_2.addWidget(self.acccheckTitle, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.acccheckScrollArea = QtWidgets.QScrollArea(self.acccheckTab)
        self.acccheckScrollArea.setWidgetResizable(True)
        self.acccheckScrollArea.setObjectName("acccheckScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 515, 808))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.acccheckButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.acccheckButton.setObjectName("acccheckButton")
        self.gridLayout_6.addWidget(self.acccheckButton, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem, 9, 0, 1, 1)
        self.acccheckH4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.acccheckH4.setFont(font)
        self.acccheckH4.setObjectName("acccheckH4")
        self.gridLayout_6.addWidget(self.acccheckH4, 7, 0, 1, 1)
        self.acccheckB3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.acccheckB3.setObjectName("acccheckB3")
        self.gridLayout_6.addWidget(self.acccheckB3, 5, 0, 1, 1)
        self.acccheckB1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.acccheckB1.setObjectName("acccheckB1")
        self.gridLayout_6.addWidget(self.acccheckB1, 1, 0, 1, 1)
        self.acccheckH2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.acccheckH2.setFont(font)
        self.acccheckH2.setObjectName("acccheckH2")
        self.gridLayout_6.addWidget(self.acccheckH2, 2, 0, 1, 1)
        self.acccheckH1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.acccheckH1.setFont(font)
        self.acccheckH1.setObjectName("acccheckH1")
        self.gridLayout_6.addWidget(self.acccheckH1, 0, 0, 1, 1)
        self.acccheckB2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.acccheckB2.setObjectName("acccheckB2")
        self.gridLayout_6.addWidget(self.acccheckB2, 3, 0, 1, 1)
        self.acccheckH3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.acccheckH3.setFont(font)
        self.acccheckH3.setObjectName("acccheckH3")
        self.gridLayout_6.addWidget(self.acccheckH3, 4, 0, 1, 1)
        self.acccheckB4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.acccheckB4.setObjectName("acccheckB4")
        self.gridLayout_6.addWidget(self.acccheckB4, 6, 0, 1, 1)
        self.acccheckScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.acccheckScrollArea, 1, 0, 1, 1)
        self.tabWidget.addTab(self.acccheckTab, "")
        self.toolNameTab = QtWidgets.QWidget()
        self.toolNameTab.setObjectName("toolNameTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.toolNameTab)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ToolNameTitle = QtWidgets.QLabel(self.toolNameTab)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ToolNameTitle.setFont(font)
        self.ToolNameTitle.setObjectName("ToolNameTitle")
        self.gridLayout_5.addWidget(self.ToolNameTitle, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolScrollArea = QtWidgets.QScrollArea(self.toolNameTab)
        self.toolScrollArea.setWidgetResizable(True)
        self.toolScrollArea.setObjectName("toolScrollArea")
        self.toolScrollAreaContents = QtWidgets.QWidget()
        self.toolScrollAreaContents.setGeometry(QtCore.QRect(0, 0, 500, 352))
        self.toolScrollAreaContents.setObjectName("toolScrollAreaContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.toolScrollAreaContents)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toolButton = QtWidgets.QPushButton(self.toolScrollAreaContents)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_7.addWidget(self.toolButton, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem1, 9, 0, 1, 1)
        self.toolH4 = QtWidgets.QLabel(self.toolScrollAreaContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.toolH4.setFont(font)
        self.toolH4.setObjectName("toolH4")
        self.gridLayout_7.addWidget(self.toolH4, 7, 0, 1, 1)
        self.toolB3 = QtWidgets.QLabel(self.toolScrollAreaContents)
        self.toolB3.setObjectName("toolB3")
        self.gridLayout_7.addWidget(self.toolB3, 5, 0, 1, 1)
        self.toolB1 = QtWidgets.QLabel(self.toolScrollAreaContents)
        self.toolB1.setObjectName("toolB1")
        self.gridLayout_7.addWidget(self.toolB1, 1, 0, 1, 1)
        self.toolH2 = QtWidgets.QLabel(self.toolScrollAreaContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.toolH2.setFont(font)
        self.toolH2.setObjectName("toolH2")
        self.gridLayout_7.addWidget(self.toolH2, 2, 0, 1, 1)
        self.toolH1 = QtWidgets.QLabel(self.toolScrollAreaContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.toolH1.setFont(font)
        self.toolH1.setObjectName("toolH1")
        self.gridLayout_7.addWidget(self.toolH1, 0, 0, 1, 1)
        self.toolB2 = QtWidgets.QLabel(self.toolScrollAreaContents)
        self.toolB2.setObjectName("toolB2")
        self.gridLayout_7.addWidget(self.toolB2, 3, 0, 1, 1)
        self.toolH3 = QtWidgets.QLabel(self.toolScrollAreaContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.toolH3.setFont(font)
        self.toolH3.setObjectName("toolH3")
        self.gridLayout_7.addWidget(self.toolH3, 4, 0, 1, 1)
        self.toolB4 = QtWidgets.QLabel(self.toolScrollAreaContents)
        self.toolB4.setObjectName("toolB4")
        self.gridLayout_7.addWidget(self.toolB4, 6, 0, 1, 1)
        self.toolScrollArea.setWidget(self.toolScrollAreaContents)
        self.gridLayout_5.addWidget(self.toolScrollArea, 1, 0, 1, 1)
        self.tabWidget.addTab(self.toolNameTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 772, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuWindow = QtWidgets.QMenu(self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.actionClose_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_Tab.setObjectName("actionClose_Tab")
        self.actionNew_Tab = QtWidgets.QAction(MainWindow)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionEnable_Dark_Mode = QtWidgets.QAction(MainWindow)
        self.actionEnable_Dark_Mode.setObjectName("actionEnable_Dark_Mode")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionEnter_Full_Screen = QtWidgets.QAction(MainWindow)
        self.actionEnter_Full_Screen.setObjectName("actionEnter_Full_Screen")
        self.actionSelect_Next_Tab = QtWidgets.QAction(MainWindow)
        self.actionSelect_Next_Tab.setObjectName("actionSelect_Next_Tab")
        self.actionSelect_Previous_Tab = QtWidgets.QAction(MainWindow)
        self.actionSelect_Previous_Tab.setObjectName("actionSelect_Previous_Tab")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuFile.addAction(self.actionNew_Tab)
        self.menuFile.addAction(self.actionNew_Window)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_Tab)
        self.menuFile.addAction(self.actionClose_Window)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuView.addAction(self.actionEnable_Dark_Mode)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionEnter_Full_Screen)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionSelect_Next_Tab)
        self.menuWindow.addAction(self.actionSelect_Previous_Tab)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "T Y R I O N"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Kali Tools"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Information Gathering"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "acccheck"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "ace-voip"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Amap"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Automater"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "bing-ip2hosts"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "braa"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "CaseFile"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "CDPSnarf"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "cisco-torch"))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("MainWindow", "Cookie Cadger"))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("MainWindow", "copy-router-config"))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("MainWindow", "DMitry"))
        self.treeWidget.topLevelItem(0).child(12).setText(0, _translate("MainWindow", "dnmap"))
        self.treeWidget.topLevelItem(0).child(13).setText(0, _translate("MainWindow", "dsenum"))
        self.treeWidget.topLevelItem(0).child(14).setText(0, _translate("MainWindow", "dnsmap"))
        self.treeWidget.topLevelItem(0).child(15).setText(0, _translate("MainWindow", "DNSRecon"))
        self.treeWidget.topLevelItem(0).child(16).setText(0, _translate("MainWindow", "dnstracer"))
        self.treeWidget.topLevelItem(0).child(17).setText(0, _translate("MainWindow", "dnswalk"))
        self.treeWidget.topLevelItem(0).child(18).setText(0, _translate("MainWindow", "DotDotPwn"))
        self.treeWidget.topLevelItem(0).child(19).setText(0, _translate("MainWindow", "enum4linux"))
        self.treeWidget.topLevelItem(0).child(20).setText(0, _translate("MainWindow", "enumIAX"))
        self.treeWidget.topLevelItem(0).child(21).setText(0, _translate("MainWindow", "Faraday"))
        self.treeWidget.topLevelItem(0).child(22).setText(0, _translate("MainWindow", "Fierce"))
        self.treeWidget.topLevelItem(0).child(23).setText(0, _translate("MainWindow", "Firewalk"))
        self.treeWidget.topLevelItem(0).child(24).setText(0, _translate("MainWindow", "fragroute"))
        self.treeWidget.topLevelItem(0).child(25).setText(0, _translate("MainWindow", "fragrouter"))
        self.treeWidget.topLevelItem(0).child(26).setText(0, _translate("MainWindow", "Ghost Phisher"))
        self.treeWidget.topLevelItem(0).child(27).setText(0, _translate("MainWindow", "GoLismero"))
        self.treeWidget.topLevelItem(0).child(28).setText(0, _translate("MainWindow", "goofile"))
        self.treeWidget.topLevelItem(0).child(29).setText(0, _translate("MainWindow", "hping3"))
        self.treeWidget.topLevelItem(0).child(30).setText(0, _translate("MainWindow", "ident-user-enum"))
        self.treeWidget.topLevelItem(0).child(31).setText(0, _translate("MainWindow", "InTrace"))
        self.treeWidget.topLevelItem(0).child(32).setText(0, _translate("MainWindow", "iSMTP"))
        self.treeWidget.topLevelItem(0).child(33).setText(0, _translate("MainWindow", "Ibd"))
        self.treeWidget.topLevelItem(0).child(34).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(0).child(35).setText(0, _translate("MainWindow", "masscan"))
        self.treeWidget.topLevelItem(0).child(36).setText(0, _translate("MainWindow", "Metagoofil"))
        self.treeWidget.topLevelItem(0).child(37).setText(0, _translate("MainWindow", "Miranda"))
        self.treeWidget.topLevelItem(0).child(38).setText(0, _translate("MainWindow", "nbtscan-unixwiz"))
        self.treeWidget.topLevelItem(0).child(39).setText(0, _translate("MainWindow", "Nmap"))
        self.treeWidget.topLevelItem(0).child(40).setText(0, _translate("MainWindow", "ntop"))
        self.treeWidget.topLevelItem(0).child(41).setText(0, _translate("MainWindow", "p0f"))
        self.treeWidget.topLevelItem(0).child(42).setText(0, _translate("MainWindow", "Parsero"))
        self.treeWidget.topLevelItem(0).child(43).setText(0, _translate("MainWindow", "Recon-ng"))
        self.treeWidget.topLevelItem(0).child(44).setText(0, _translate("MainWindow", "SET"))
        self.treeWidget.topLevelItem(0).child(45).setText(0, _translate("MainWindow", "smtp-user-enum"))
        self.treeWidget.topLevelItem(0).child(46).setText(0, _translate("MainWindow", "snmp-check"))
        self.treeWidget.topLevelItem(0).child(47).setText(0, _translate("MainWindow", "SPARTA"))
        self.treeWidget.topLevelItem(0).child(48).setText(0, _translate("MainWindow", "sslcaudit"))
        self.treeWidget.topLevelItem(0).child(49).setText(0, _translate("MainWindow", "SSLsplit"))
        self.treeWidget.topLevelItem(0).child(50).setText(0, _translate("MainWindow", "sslstrip"))
        self.treeWidget.topLevelItem(0).child(51).setText(0, _translate("MainWindow", "SSLyze"))
        self.treeWidget.topLevelItem(0).child(52).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(0).child(53).setText(0, _translate("MainWindow", "theHarvester"))
        self.treeWidget.topLevelItem(0).child(54).setText(0, _translate("MainWindow", "TLSSLed"))
        self.treeWidget.topLevelItem(0).child(55).setText(0, _translate("MainWindow", "twofi"))
        self.treeWidget.topLevelItem(0).child(56).setText(0, _translate("MainWindow", "URLCrazy"))
        self.treeWidget.topLevelItem(0).child(57).setText(0, _translate("MainWindow", "Wireshark"))
        self.treeWidget.topLevelItem(0).child(58).setText(0, _translate("MainWindow", "WOL-E"))
        self.treeWidget.topLevelItem(0).child(59).setText(0, _translate("MainWindow", "Xplico"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Sniffing & Spoofing"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Burp Suite"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "DNSChef"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "fiked"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "hamster-sidejack"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "HexInject"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "iaxflood"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "inviteflood"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "iSMTP"))
        self.treeWidget.topLevelItem(1).child(8).setText(0, _translate("MainWindow", "isr-evilgrade"))
        self.treeWidget.topLevelItem(1).child(9).setText(0, _translate("MainWindow", "mitmproxy"))
        self.treeWidget.topLevelItem(1).child(10).setText(0, _translate("MainWindow", "ohrwurm"))
        self.treeWidget.topLevelItem(1).child(11).setText(0, _translate("MainWindow", "protos-sip"))
        self.treeWidget.topLevelItem(1).child(12).setText(0, _translate("MainWindow", "rebind"))
        self.treeWidget.topLevelItem(1).child(13).setText(0, _translate("MainWindow", "responder"))
        self.treeWidget.topLevelItem(1).child(14).setText(0, _translate("MainWindow", "rtpbreak"))
        self.treeWidget.topLevelItem(1).child(15).setText(0, _translate("MainWindow", "rtpinsertsound"))
        self.treeWidget.topLevelItem(1).child(16).setText(0, _translate("MainWindow", "rtpmixsound"))
        self.treeWidget.topLevelItem(1).child(17).setText(0, _translate("MainWindow", "sctpscan"))
        self.treeWidget.topLevelItem(1).child(18).setText(0, _translate("MainWindow", "SIPArmyKnife"))
        self.treeWidget.topLevelItem(1).child(19).setText(0, _translate("MainWindow", "SIPp"))
        self.treeWidget.topLevelItem(1).child(20).setText(0, _translate("MainWindow", "SIPVicious"))
        self.treeWidget.topLevelItem(1).child(21).setText(0, _translate("MainWindow", "SniffJoke"))
        self.treeWidget.topLevelItem(1).child(22).setText(0, _translate("MainWindow", "SSLsplit"))
        self.treeWidget.topLevelItem(1).child(23).setText(0, _translate("MainWindow", "sslstrip"))
        self.treeWidget.topLevelItem(1).child(24).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(1).child(25).setText(0, _translate("MainWindow", "VoIPHopper"))
        self.treeWidget.topLevelItem(1).child(26).setText(0, _translate("MainWindow", "WebScabar"))
        self.treeWidget.topLevelItem(1).child(27).setText(0, _translate("MainWindow", "Wifi Honey"))
        self.treeWidget.topLevelItem(1).child(28).setText(0, _translate("MainWindow", "Wireshark"))
        self.treeWidget.topLevelItem(1).child(29).setText(0, _translate("MainWindow", "xspy"))
        self.treeWidget.topLevelItem(1).child(30).setText(0, _translate("MainWindow", "Yersinia"))
        self.treeWidget.topLevelItem(1).child(31).setText(0, _translate("MainWindow", "zaproxy"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Vulnerability Analysis"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "BBQSQL"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "BED"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "cisco-auditing-tool"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "cisco-global-exploiter"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "cisco-ocs"))
        self.treeWidget.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "cisco-torch"))
        self.treeWidget.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "copy-router-config"))
        self.treeWidget.topLevelItem(2).child(7).setText(0, _translate("MainWindow", "DBPwAudit"))
        self.treeWidget.topLevelItem(2).child(8).setText(0, _translate("MainWindow", "Doona"))
        self.treeWidget.topLevelItem(2).child(9).setText(0, _translate("MainWindow", "DotDotPwn"))
        self.treeWidget.topLevelItem(2).child(10).setText(0, _translate("MainWindow", "Greenbone Security Assistant"))
        self.treeWidget.topLevelItem(2).child(11).setText(0, _translate("MainWindow", "GSD"))
        self.treeWidget.topLevelItem(2).child(12).setText(0, _translate("MainWindow", "HexorBase"))
        self.treeWidget.topLevelItem(2).child(13).setText(0, _translate("MainWindow", "Inguma"))
        self.treeWidget.topLevelItem(2).child(14).setText(0, _translate("MainWindow", "jSQL"))
        self.treeWidget.topLevelItem(2).child(15).setText(0, _translate("MainWindow", "Lynis"))
        self.treeWidget.topLevelItem(2).child(16).setText(0, _translate("MainWindow", "Nmap"))
        self.treeWidget.topLevelItem(2).child(17).setText(0, _translate("MainWindow", "ohrwurm"))
        self.treeWidget.topLevelItem(2).child(18).setText(0, _translate("MainWindow", "openvas-adminstrator"))
        self.treeWidget.topLevelItem(2).child(19).setText(0, _translate("MainWindow", "openvas-scanner"))
        self.treeWidget.topLevelItem(2).child(20).setText(0, _translate("MainWindow", "Oscanner"))
        self.treeWidget.topLevelItem(2).child(21).setText(0, _translate("MainWindow", "sfuzz"))
        self.treeWidget.topLevelItem(2).child(22).setText(0, _translate("MainWindow", "SidGuesser"))
        self.treeWidget.topLevelItem(2).child(23).setText(0, _translate("MainWindow", "SIPArmyKnife"))
        self.treeWidget.topLevelItem(2).child(24).setText(0, _translate("MainWindow", "sqlmap"))
        self.treeWidget.topLevelItem(2).child(25).setText(0, _translate("MainWindow", "Sqlninja"))
        self.treeWidget.topLevelItem(2).child(26).setText(0, _translate("MainWindow", "sqlsus"))
        self.treeWidget.topLevelItem(2).child(27).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(2).child(28).setText(0, _translate("MainWindow", "tnscmd10g"))
        self.treeWidget.topLevelItem(2).child(29).setText(0, _translate("MainWindow", "unix-privesc-check"))
        self.treeWidget.topLevelItem(2).child(30).setText(0, _translate("MainWindow", "Yersinia"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Exploitation"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Armitage"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Backdoor Factory"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "BeEF"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "cisco-auditing-tool"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "cisco-global-exploiter"))
        self.treeWidget.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "cisco-ocs"))
        self.treeWidget.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "cisco-torch"))
        self.treeWidget.topLevelItem(3).child(7).setText(0, _translate("MainWindow", "Commix"))
        self.treeWidget.topLevelItem(3).child(8).setText(0, _translate("MainWindow", "crackle"))
        self.treeWidget.topLevelItem(3).child(9).setText(0, _translate("MainWindow", "jboss-autopwn"))
        self.treeWidget.topLevelItem(3).child(10).setText(0, _translate("MainWindow", "Linux Exploit Suggester"))
        self.treeWidget.topLevelItem(3).child(11).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(3).child(12).setText(0, _translate("MainWindow", "SET"))
        self.treeWidget.topLevelItem(3).child(13).setText(0, _translate("MainWindow", "ShellNoob"))
        self.treeWidget.topLevelItem(3).child(14).setText(0, _translate("MainWindow", "sqlmap"))
        self.treeWidget.topLevelItem(3).child(15).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(3).child(16).setText(0, _translate("MainWindow", "Yersinia"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Password Attacks"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "acccheck"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Burp Suite"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "CeWL"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "chnptw"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "cisco-auditing-tool"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "CmosPwd"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("MainWindow", "creddump"))
        self.treeWidget.topLevelItem(4).child(7).setText(0, _translate("MainWindow", "crunch"))
        self.treeWidget.topLevelItem(4).child(8).setText(0, _translate("MainWindow", "DBPwAudit"))
        self.treeWidget.topLevelItem(4).child(9).setText(0, _translate("MainWindow", "findmyhash"))
        self.treeWidget.topLevelItem(4).child(10).setText(0, _translate("MainWindow", "gpp-decrypt"))
        self.treeWidget.topLevelItem(4).child(11).setText(0, _translate("MainWindow", "hash-identifier"))
        self.treeWidget.topLevelItem(4).child(12).setText(0, _translate("MainWindow", "HexorBase"))
        self.treeWidget.topLevelItem(4).child(13).setText(0, _translate("MainWindow", "THC-Hydra"))
        self.treeWidget.topLevelItem(4).child(14).setText(0, _translate("MainWindow", "John the Ripper"))
        self.treeWidget.topLevelItem(4).child(15).setText(0, _translate("MainWindow", "Johnny"))
        self.treeWidget.topLevelItem(4).child(16).setText(0, _translate("MainWindow", "keimpx"))
        self.treeWidget.topLevelItem(4).child(17).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(4).child(18).setText(0, _translate("MainWindow", "Maskprocessor"))
        self.treeWidget.topLevelItem(4).child(19).setText(0, _translate("MainWindow", "multiforcer"))
        self.treeWidget.topLevelItem(4).child(20).setText(0, _translate("MainWindow", "Ncrack"))
        self.treeWidget.topLevelItem(4).child(21).setText(0, _translate("MainWindow", "oclgausscrack"))
        self.treeWidget.topLevelItem(4).child(22).setText(0, _translate("MainWindow", "PACK"))
        self.treeWidget.topLevelItem(4).child(23).setText(0, _translate("MainWindow", "patator"))
        self.treeWidget.topLevelItem(4).child(24).setText(0, _translate("MainWindow", "phrasendrescher"))
        self.treeWidget.topLevelItem(4).child(25).setText(0, _translate("MainWindow", "polenum"))
        self.treeWidget.topLevelItem(4).child(26).setText(0, _translate("MainWindow", "RainbowCrack"))
        self.treeWidget.topLevelItem(4).child(27).setText(0, _translate("MainWindow", "rcracki-mt"))
        self.treeWidget.topLevelItem(4).child(28).setText(0, _translate("MainWindow", "RSMangler"))
        self.treeWidget.topLevelItem(4).child(29).setText(0, _translate("MainWindow", "SQLdict"))
        self.treeWidget.topLevelItem(4).child(30).setText(0, _translate("MainWindow", "Statsprocessor"))
        self.treeWidget.topLevelItem(4).child(31).setText(0, _translate("MainWindow", "THC-pptp-bruter"))
        self.treeWidget.topLevelItem(4).child(32).setText(0, _translate("MainWindow", "TrueCrack"))
        self.treeWidget.topLevelItem(4).child(33).setText(0, _translate("MainWindow", "WebScarab"))
        self.treeWidget.topLevelItem(4).child(34).setText(0, _translate("MainWindow", "wordlists"))
        self.treeWidget.topLevelItem(4).child(35).setText(0, _translate("MainWindow", "zaproxy"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Wireless Attacks"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Aircrack-ng"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Asleap"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Bluelog"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "BlueMaho"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "Bluepot"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "BlueRanger"))
        self.treeWidget.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "Bluesnarfer"))
        self.treeWidget.topLevelItem(5).child(7).setText(0, _translate("MainWindow", "Bully"))
        self.treeWidget.topLevelItem(5).child(8).setText(0, _translate("MainWindow", "coWPAtty"))
        self.treeWidget.topLevelItem(5).child(9).setText(0, _translate("MainWindow", "crackle"))
        self.treeWidget.topLevelItem(5).child(10).setText(0, _translate("MainWindow", "eapmd5pass"))
        self.treeWidget.topLevelItem(5).child(11).setText(0, _translate("MainWindow", "Fern Wifi Cracker"))
        self.treeWidget.topLevelItem(5).child(12).setText(0, _translate("MainWindow", "Ghost Phisher"))
        self.treeWidget.topLevelItem(5).child(13).setText(0, _translate("MainWindow", "GISKismet"))
        self.treeWidget.topLevelItem(5).child(14).setText(0, _translate("MainWindow", "Gqrx"))
        self.treeWidget.topLevelItem(5).child(15).setText(0, _translate("MainWindow", "gr-scan"))
        self.treeWidget.topLevelItem(5).child(16).setText(0, _translate("MainWindow", "hostapd-wpe"))
        self.treeWidget.topLevelItem(5).child(17).setText(0, _translate("MainWindow", "kalibrate-rtl"))
        self.treeWidget.topLevelItem(5).child(18).setText(0, _translate("MainWindow", "KillerBee"))
        self.treeWidget.topLevelItem(5).child(19).setText(0, _translate("MainWindow", "Kismet"))
        self.treeWidget.topLevelItem(5).child(20).setText(0, _translate("MainWindow", "mdk3"))
        self.treeWidget.topLevelItem(5).child(21).setText(0, _translate("MainWindow", "mfcuk"))
        self.treeWidget.topLevelItem(5).child(22).setText(0, _translate("MainWindow", "mfoc"))
        self.treeWidget.topLevelItem(5).child(23).setText(0, _translate("MainWindow", "mfterm"))
        self.treeWidget.topLevelItem(5).child(24).setText(0, _translate("MainWindow", "Multimon-NG"))
        self.treeWidget.topLevelItem(5).child(25).setText(0, _translate("MainWindow", "PixieWPS"))
        self.treeWidget.topLevelItem(5).child(26).setText(0, _translate("MainWindow", "Reaver"))
        self.treeWidget.topLevelItem(5).child(27).setText(0, _translate("MainWindow", "redfang"))
        self.treeWidget.topLevelItem(5).child(28).setText(0, _translate("MainWindow", "RTLSDR Scanner"))
        self.treeWidget.topLevelItem(5).child(29).setText(0, _translate("MainWindow", "Spooftooph"))
        self.treeWidget.topLevelItem(5).child(30).setText(0, _translate("MainWindow", "Wifi Honey"))
        self.treeWidget.topLevelItem(5).child(31).setText(0, _translate("MainWindow", "wifiphisher"))
        self.treeWidget.topLevelItem(5).child(32).setText(0, _translate("MainWindow", "Wifitap"))
        self.treeWidget.topLevelItem(5).child(33).setText(0, _translate("MainWindow", "Wifite"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "Forensics"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "Binwalk"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "bulk-extractor"))
        self.treeWidget.topLevelItem(6).child(2).setText(0, _translate("MainWindow", "Capstone"))
        self.treeWidget.topLevelItem(6).child(3).setText(0, _translate("MainWindow", "chntpw"))
        self.treeWidget.topLevelItem(6).child(4).setText(0, _translate("MainWindow", "Cuckoo"))
        self.treeWidget.topLevelItem(6).child(5).setText(0, _translate("MainWindow", "dc3dd"))
        self.treeWidget.topLevelItem(6).child(6).setText(0, _translate("MainWindow", "ddrescue"))
        self.treeWidget.topLevelItem(6).child(7).setText(0, _translate("MainWindow", "DFF"))
        self.treeWidget.topLevelItem(6).child(8).setText(0, _translate("MainWindow", "diStorm3"))
        self.treeWidget.topLevelItem(6).child(9).setText(0, _translate("MainWindow", "Dumpzilla"))
        self.treeWidget.topLevelItem(6).child(10).setText(0, _translate("MainWindow", "extundelete"))
        self.treeWidget.topLevelItem(6).child(11).setText(0, _translate("MainWindow", "Foremost"))
        self.treeWidget.topLevelItem(6).child(12).setText(0, _translate("MainWindow", "Galleta"))
        self.treeWidget.topLevelItem(6).child(13).setText(0, _translate("MainWindow", "Guymager"))
        self.treeWidget.topLevelItem(6).child(14).setText(0, _translate("MainWindow", "iPhone Backup Analyzer"))
        self.treeWidget.topLevelItem(6).child(15).setText(0, _translate("MainWindow", "p0f"))
        self.treeWidget.topLevelItem(6).child(16).setText(0, _translate("MainWindow", "pdf-parser"))
        self.treeWidget.topLevelItem(6).child(17).setText(0, _translate("MainWindow", "pdfid"))
        self.treeWidget.topLevelItem(6).child(18).setText(0, _translate("MainWindow", "pdgmail"))
        self.treeWidget.topLevelItem(6).child(19).setText(0, _translate("MainWindow", "peepdf"))
        self.treeWidget.topLevelItem(6).child(20).setText(0, _translate("MainWindow", "RegRipper"))
        self.treeWidget.topLevelItem(6).child(21).setText(0, _translate("MainWindow", "Volatility"))
        self.treeWidget.topLevelItem(6).child(22).setText(0, _translate("MainWindow", "Xplico"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "Maintaining Access"))
        self.treeWidget.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "CryptCat"))
        self.treeWidget.topLevelItem(7).child(1).setText(0, _translate("MainWindow", "Cymothoa"))
        self.treeWidget.topLevelItem(7).child(2).setText(0, _translate("MainWindow", "dbd"))
        self.treeWidget.topLevelItem(7).child(3).setText(0, _translate("MainWindow", "dns2tcp"))
        self.treeWidget.topLevelItem(7).child(4).setText(0, _translate("MainWindow", "http-tunnel"))
        self.treeWidget.topLevelItem(7).child(5).setText(0, _translate("MainWindow", "HTTPTunnel"))
        self.treeWidget.topLevelItem(7).child(6).setText(0, _translate("MainWindow", "Intersect"))
        self.treeWidget.topLevelItem(7).child(7).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(7).child(8).setText(0, _translate("MainWindow", "Nishang"))
        self.treeWidget.topLevelItem(7).child(9).setText(0, _translate("MainWindow", "polenum"))
        self.treeWidget.topLevelItem(7).child(10).setText(0, _translate("MainWindow", "PowerSploit"))
        self.treeWidget.topLevelItem(7).child(11).setText(0, _translate("MainWindow", "pwnat"))
        self.treeWidget.topLevelItem(7).child(12).setText(0, _translate("MainWindow", "RidEnum"))
        self.treeWidget.topLevelItem(7).child(13).setText(0, _translate("MainWindow", "sbd"))
        self.treeWidget.topLevelItem(7).child(14).setText(0, _translate("MainWindow", "U3-Pwn"))
        self.treeWidget.topLevelItem(7).child(15).setText(0, _translate("MainWindow", "Webshells"))
        self.treeWidget.topLevelItem(7).child(16).setText(0, _translate("MainWindow", "Weevely"))
        self.treeWidget.topLevelItem(7).child(17).setText(0, _translate("MainWindow", "Winexe"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "Hardware Hacking"))
        self.treeWidget.topLevelItem(8).child(0).setText(0, _translate("MainWindow", "android-sdk"))
        self.treeWidget.topLevelItem(8).child(1).setText(0, _translate("MainWindow", "apktool"))
        self.treeWidget.topLevelItem(8).child(2).setText(0, _translate("MainWindow", "Arduino"))
        self.treeWidget.topLevelItem(8).child(3).setText(0, _translate("MainWindow", "dex2jar"))
        self.treeWidget.topLevelItem(8).child(4).setText(0, _translate("MainWindow", "Sakis3G"))
        self.treeWidget.topLevelItem(8).child(5).setText(0, _translate("MainWindow", "smali"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "Web Applications"))
        self.treeWidget.topLevelItem(9).child(0).setText(0, _translate("MainWindow", "apache-users"))
        self.treeWidget.topLevelItem(9).child(1).setText(0, _translate("MainWindow", "Arachni"))
        self.treeWidget.topLevelItem(9).child(2).setText(0, _translate("MainWindow", "BBQSQL"))
        self.treeWidget.topLevelItem(9).child(3).setText(0, _translate("MainWindow", "BlindElephant"))
        self.treeWidget.topLevelItem(9).child(4).setText(0, _translate("MainWindow", "Burp Suite"))
        self.treeWidget.topLevelItem(9).child(5).setText(0, _translate("MainWindow", "CutyCapt"))
        self.treeWidget.topLevelItem(9).child(6).setText(0, _translate("MainWindow", "DAVTest"))
        self.treeWidget.topLevelItem(9).child(7).setText(0, _translate("MainWindow", "deblaze"))
        self.treeWidget.topLevelItem(9).child(8).setText(0, _translate("MainWindow", "DIRB"))
        self.treeWidget.topLevelItem(9).child(9).setText(0, _translate("MainWindow", "DirBuster"))
        self.treeWidget.topLevelItem(9).child(10).setText(0, _translate("MainWindow", "fimap"))
        self.treeWidget.topLevelItem(9).child(11).setText(0, _translate("MainWindow", "FunkLoad"))
        self.treeWidget.topLevelItem(9).child(12).setText(0, _translate("MainWindow", "Gobuster"))
        self.treeWidget.topLevelItem(9).child(13).setText(0, _translate("MainWindow", "Grabber"))
        self.treeWidget.topLevelItem(9).child(14).setText(0, _translate("MainWindow", "jboss-autopwn"))
        self.treeWidget.topLevelItem(9).child(15).setText(0, _translate("MainWindow", "joomscan"))
        self.treeWidget.topLevelItem(9).child(16).setText(0, _translate("MainWindow", "jSQL"))
        self.treeWidget.topLevelItem(9).child(17).setText(0, _translate("MainWindow", "Maltego Teeth"))
        self.treeWidget.topLevelItem(9).child(18).setText(0, _translate("MainWindow", "PadBuster"))
        self.treeWidget.topLevelItem(9).child(19).setText(0, _translate("MainWindow", "Paros"))
        self.treeWidget.topLevelItem(9).child(20).setText(0, _translate("MainWindow", "Parsero"))
        self.treeWidget.topLevelItem(9).child(21).setText(0, _translate("MainWindow", "plecost"))
        self.treeWidget.topLevelItem(9).child(22).setText(0, _translate("MainWindow", "Powerfuzzer"))
        self.treeWidget.topLevelItem(9).child(23).setText(0, _translate("MainWindow", "ProxyStrike"))
        self.treeWidget.topLevelItem(9).child(24).setText(0, _translate("MainWindow", "Recon-ng"))
        self.treeWidget.topLevelItem(9).child(25).setText(0, _translate("MainWindow", "Skipfish"))
        self.treeWidget.topLevelItem(9).child(26).setText(0, _translate("MainWindow", "sqlmap"))
        self.treeWidget.topLevelItem(9).child(27).setText(0, _translate("MainWindow", "Sqlninja"))
        self.treeWidget.topLevelItem(9).child(28).setText(0, _translate("MainWindow", "sqlsus"))
        self.treeWidget.topLevelItem(9).child(29).setText(0, _translate("MainWindow", "ua-tester"))
        self.treeWidget.topLevelItem(9).child(30).setText(0, _translate("MainWindow", "Uniscan"))
        self.treeWidget.topLevelItem(9).child(31).setText(0, _translate("MainWindow", "Vega"))
        self.treeWidget.topLevelItem(9).child(32).setText(0, _translate("MainWindow", "w3af"))
        self.treeWidget.topLevelItem(9).child(33).setText(0, _translate("MainWindow", "WebScarab"))
        self.treeWidget.topLevelItem(9).child(34).setText(0, _translate("MainWindow", "Webshag"))
        self.treeWidget.topLevelItem(9).child(35).setText(0, _translate("MainWindow", "WebSlayer"))
        self.treeWidget.topLevelItem(9).child(36).setText(0, _translate("MainWindow", "WebSploit"))
        self.treeWidget.topLevelItem(9).child(37).setText(0, _translate("MainWindow", "Wfuzz"))
        self.treeWidget.topLevelItem(9).child(38).setText(0, _translate("MainWindow", "WPScan"))
        self.treeWidget.topLevelItem(9).child(39).setText(0, _translate("MainWindow", "XSSer"))
        self.treeWidget.topLevelItem(9).child(40).setText(0, _translate("MainWindow", "zaproxy"))
        self.treeWidget.topLevelItem(10).setText(0, _translate("MainWindow", "Stress Testing"))
        self.treeWidget.topLevelItem(10).child(0).setText(0, _translate("MainWindow", "DHCPig"))
        self.treeWidget.topLevelItem(10).child(1).setText(0, _translate("MainWindow", "FunkLoad"))
        self.treeWidget.topLevelItem(10).child(2).setText(0, _translate("MainWindow", "iaxflood"))
        self.treeWidget.topLevelItem(10).child(3).setText(0, _translate("MainWindow", "Inundator"))
        self.treeWidget.topLevelItem(10).child(4).setText(0, _translate("MainWindow", "inviteflood"))
        self.treeWidget.topLevelItem(10).child(5).setText(0, _translate("MainWindow", "ipv6-toolkit"))
        self.treeWidget.topLevelItem(10).child(6).setText(0, _translate("MainWindow", "mdk3"))
        self.treeWidget.topLevelItem(10).child(7).setText(0, _translate("MainWindow", "Reaver"))
        self.treeWidget.topLevelItem(10).child(8).setText(0, _translate("MainWindow", "rtpflood"))
        self.treeWidget.topLevelItem(10).child(9).setText(0, _translate("MainWindow", "SlowHTTPTest"))
        self.treeWidget.topLevelItem(10).child(10).setText(0, _translate("MainWindow", "t50"))
        self.treeWidget.topLevelItem(10).child(11).setText(0, _translate("MainWindow", "Termineter"))
        self.treeWidget.topLevelItem(10).child(12).setText(0, _translate("MainWindow", "THC-IPV6"))
        self.treeWidget.topLevelItem(10).child(13).setText(0, _translate("MainWindow", "THC-SSL-DOS"))
        self.treeWidget.topLevelItem(11).setText(0, _translate("MainWindow", "Reverse Engineering"))
        self.treeWidget.topLevelItem(11).child(0).setText(0, _translate("MainWindow", "apktool"))
        self.treeWidget.topLevelItem(11).child(1).setText(0, _translate("MainWindow", "dex2jar"))
        self.treeWidget.topLevelItem(11).child(2).setText(0, _translate("MainWindow", "diStorm3"))
        self.treeWidget.topLevelItem(11).child(3).setText(0, _translate("MainWindow", "edb-debugger"))
        self.treeWidget.topLevelItem(11).child(4).setText(0, _translate("MainWindow", "jad"))
        self.treeWidget.topLevelItem(11).child(5).setText(0, _translate("MainWindow", "javasnoop"))
        self.treeWidget.topLevelItem(11).child(6).setText(0, _translate("MainWindow", "JD-GUI"))
        self.treeWidget.topLevelItem(11).child(7).setText(0, _translate("MainWindow", "OllyDbg"))
        self.treeWidget.topLevelItem(11).child(8).setText(0, _translate("MainWindow", "smali"))
        self.treeWidget.topLevelItem(11).child(9).setText(0, _translate("MainWindow", "Valgrind"))
        self.treeWidget.topLevelItem(11).child(10).setText(0, _translate("MainWindow", "YARA"))
        self.treeWidget.topLevelItem(12).setText(0, _translate("MainWindow", "Reporting"))
        self.treeWidget.topLevelItem(12).child(0).setText(0, _translate("MainWindow", "CaseFile"))
        self.treeWidget.topLevelItem(12).child(1).setText(0, _translate("MainWindow", "CutyCapt"))
        self.treeWidget.topLevelItem(12).child(2).setText(0, _translate("MainWindow", "dos2unix"))
        self.treeWidget.topLevelItem(12).child(3).setText(0, _translate("MainWindow", "Dradis"))
        self.treeWidget.topLevelItem(12).child(4).setText(0, _translate("MainWindow", "KeepNote"))
        self.treeWidget.topLevelItem(12).child(5).setText(0, _translate("MainWindow", "MagicTree"))
        self.treeWidget.topLevelItem(12).child(6).setText(0, _translate("MainWindow", "Metagoofil"))
        self.treeWidget.topLevelItem(12).child(7).setText(0, _translate("MainWindow", "Nipper-ng"))
        self.treeWidget.topLevelItem(12).child(8).setText(0, _translate("MainWindow", "pipal"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.appNameLabel.setText(_translate("MainWindow", "T Y R I O N"))
        self.versionLabel.setText(_translate("MainWindow", "V e r s i o n   1 . 0"))
        self.descLabel.setText(_translate("MainWindow", "AN ALL-IN-ONE KALI LINUX TOOL MANAGEMENT APP "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcomeTab), _translate("MainWindow", "Welcome"))
        self.braaLabel.setText(_translate("MainWindow", "braa"))
        self.DMitryLabel.setText(_translate("MainWindow", "DMitry"))
        self.AmapLabel.setText(_translate("MainWindow", "Amap"))
        self.CDPSnarfLabel.setText(_translate("MainWindow", "CDPSnarf"))
        self.enum4linuxLabel.setText(_translate("MainWindow", "enum4linux"))
        self.dsenumLabel.setText(_translate("MainWindow", "dsenum"))
        self.GhostPhisherLabel.setText(_translate("MainWindow", "Ghost Phisher"))
        self.CookieCadgerLabel.setText(_translate("MainWindow", "Cookie Cadger"))
        self.FierceLabel.setText(_translate("MainWindow", "Fierce"))
        self.DNSReconLabel.setText(_translate("MainWindow", "DNSRecon"))
        self.hping3Label.setText(_translate("MainWindow", "hping3"))
        self.dnstracerLabel.setText(_translate("MainWindow", "dnstracer"))
        self.goofileLabel.setText(_translate("MainWindow", "goofile"))
        self.aceVoipLabel.setText(_translate("MainWindow", "ace-voip"))
        self.CaseFileLabel.setText(_translate("MainWindow", "CaseFile"))
        self.AutomaterLabel.setText(_translate("MainWindow", "Automater"))
        self.enumIAXLabel.setText(_translate("MainWindow", "enumIAX"))
        self.bingIp2hostsLabel.setText(_translate("MainWindow", "bing-ip2hosts"))
        self.FireWalkLabel.setText(_translate("MainWindow", "Firewalk"))
        self.GoLismero.setText(_translate("MainWindow", "GoLismero"))
        self.fragRouterLabel.setText(_translate("MainWindow", "fragrouter"))
        self.dnsmapLabel.setText(_translate("MainWindow", "dnsmap"))
        self.fragRouteLabel.setText(_translate("MainWindow", "fragroute"))
        self.FaradayLabel.setText(_translate("MainWindow", "Faraday"))
        self.copyRouterConfigLabel.setText(_translate("MainWindow", "copy-router-config"))
        self.ciscoTorchLabel.setText(_translate("MainWindow", "cisco-torch"))
        self.dnswalkLabel.setText(_translate("MainWindow", "dnswalk"))
        self.acccheckLabel.setText(_translate("MainWindow", "acccheck"))
        self.DotDotPwnLabel.setText(_translate("MainWindow", "DotDotPwn"))
        self.dnmapLabel.setText(_translate("MainWindow", "dnmap"))
        self.identUserEnumLabel.setText(_translate("MainWindow", "ident-user-enum"))
        self.InTraceLabel.setText(_translate("MainWindow", "InTrace"))
        self.SMTPLabel.setText(_translate("MainWindow", "iSMTP"))
        self.IbdLabel.setText(_translate("MainWindow", "Ibd"))
        self.MaltegoTeethLabel.setText(_translate("MainWindow", "Maltego Teeth"))
        self.masscanLabel.setText(_translate("MainWindow", "masscan"))
        self.MetagoofilLabel.setText(_translate("MainWindow", "Metagoofil"))
        self.MirandaLabel.setText(_translate("MainWindow", "Miranda"))
        self.nbtscanUnixwizLabel.setText(_translate("MainWindow", "nbtscan-unixwiz"))
        self.NmapLabel.setText(_translate("MainWindow", "Nmap"))
        self.ntopLabel.setText(_translate("MainWindow", "ntop"))
        self.p0fLabel.setText(_translate("MainWindow", "p0f"))
        self.ParseroLabel.setText(_translate("MainWindow", "Parsero"))
        self.ReconNgLabel.setText(_translate("MainWindow", "Recon-ng"))
        self.SETLabel.setText(_translate("MainWindow", "SET"))
        self.smtpUserEnumLabel.setText(_translate("MainWindow", "smtp-user-enum"))
        self.snmpCheckLabel.setText(_translate("MainWindow", "snmp-check"))
        self.SPARTALabel.setText(_translate("MainWindow", "SPARTA"))
        self.sslcauditLabel.setText(_translate("MainWindow", "sslcaudit"))
        self.SSLsplitLabel.setText(_translate("MainWindow", "SSLsplit"))
        self.sslstripLabel.setText(_translate("MainWindow", "sslstrip"))
        self.SSLyzeLabel.setText(_translate("MainWindow", "SSLyze"))
        self.THCIPV6Label.setText(_translate("MainWindow", "THC-IPV6"))
        self.theHarvesterLabel.setText(_translate("MainWindow", "theHarvester"))
        self.TLSSLedLabel.setText(_translate("MainWindow", "TLSSLed"))
        self.twofiLabel.setText(_translate("MainWindow", "twofi"))
        self.URLCrazyLabel.setText(_translate("MainWindow", "URLCrazy"))
        self.WiresharkLabel.setText(_translate("MainWindow", "Wireshark"))
        self.WOLELabel.setText(_translate("MainWindow", "WOL-E"))
        self.XplicoLabel.setText(_translate("MainWindow", "Xplico"))
        self.InformationGatheringTitle.setText(_translate("MainWindow", "Information Gathering"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoGatheringTab), _translate("MainWindow", "Information Gathering"))
        self.acccheckTitle.setText(_translate("MainWindow", "acccheck"))
        self.acccheckButton.setText(_translate("MainWindow", "./accheck"))
        self.acccheckH4.setText(_translate("MainWindow", "RUN ON TERMINAL :"))
        self.acccheckB3.setText(_translate("MainWindow", "Attempt the \'Administrator\' account with a [BLANK] password.\n"
"acccheck -t 10.10.10.1\n"
"Attempt all passwords in \'password.txt\' against the \'Administrator\' account.\n"
"acccheck -t 10.10.10.1 -P password.txt\n"
"Attempt all password in \'password.txt\' against all users in \'users.txt\'.\n"
"acccehck -t 10.10.10.1 -U users.txt -P password.txt\n"
"Attempt a single password against a single user.\n"
"acccheck -t 10.10.10.1 -u administrator -p password "))
        self.acccheckB1.setText(_translate("MainWindow", "acccheck v0.2.1 - By Faiz\n"
"\n"
"The tool is designed as a password dictionary attack tool that targets windows\n"
"authentication via the SMB protocol. It is really a wrapper script around\n"
"the ‘smbclient’ binary, and as a result is dependent on it for its execution.\n"
"\n"
"Attempts to connect to the IPC$ and ADMIN$ shares depending on which\n"
"flags have been chosen, and tries a combination of usernames and passwords\n"
"in the hope to identify the password to a given account via a dictionary password\n"
"guessing attack.\n"
""))
        self.acccheckH2.setText(_translate("MainWindow", "Usage:"))
        self.acccheckH1.setText(_translate("MainWindow", "Description:"))
        self.acccheckB2.setText(_translate("MainWindow", "./acccheck [optional]\n"
"\n"
"-t [single host IP address]\n"
"OR\n"
"-T [file containing target ip address(es)]\n"
"\n"
"Optional:\n"
"-p [single password]\n"
"-P [file containing passwords]\n"
"-u [single user]\n"
"-U [file containing usernames]\n"
"-v [verbose mode] "))
        self.acccheckH3.setText(_translate("MainWindow", "Examples:"))
        self.acccheckB4.setText(_translate("MainWindow", "root@kali:~# acccheck.pl -T smb-ips.txt -v\n"
"Host:192.168.1.201, Username:Administrator, Password:BLANK\n"
""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acccheckTab), _translate("MainWindow", "acccheck"))
        self.ToolNameTitle.setText(_translate("MainWindow", "ToolName"))
        self.toolButton.setText(_translate("MainWindow", "Button"))
        self.toolH4.setText(_translate("MainWindow", "RUN ON TERMINAL :"))
        self.toolB3.setText(_translate("MainWindow", "BODY 3"))
        self.toolB1.setText(_translate("MainWindow", "BODY 1"))
        self.toolH2.setText(_translate("MainWindow", "Usage:"))
        self.toolH1.setText(_translate("MainWindow", "Description:"))
        self.toolB2.setText(_translate("MainWindow", "BODY 2"))
        self.toolH3.setText(_translate("MainWindow", "Examples:"))
        self.toolB4.setText(_translate("MainWindow", "BODY4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.toolNameTab), _translate("MainWindow", "ToolName"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionClose_Window.setText(_translate("MainWindow", "Close Window"))
        self.actionClose_Tab.setText(_translate("MainWindow", "Close Tab"))
        self.actionNew_Tab.setText(_translate("MainWindow", "New Tab"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionEnable_Dark_Mode.setText(_translate("MainWindow", "Enable Dark Mode"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionEnter_Full_Screen.setText(_translate("MainWindow", "Enter Full Screen"))
        self.actionSelect_Next_Tab.setText(_translate("MainWindow", "Select Next Tab"))
        self.actionSelect_Previous_Tab.setText(_translate("MainWindow", "Select Previous Tab"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))

